[workspace]
resolver = "2"
members = ["tauri", "boa_utils"]

[workspace.package]
repository = "https://github.com/keiko233/clash-nyanpasu.git"
edition = "2021"
license = "GPL-3.0"
authors = ["zzzgydi", "keiko233"]

[workspace.dependencies]
thiserror = "1"
tracing = "0.1"
boa_engine = { version = "0.19", git = "https://github.com/boa-dev/boa.git", branch = "backport-0.19-fixes" }

[profile.release]
panic = "unwind"
codegen-units = 1
lto = true
opt-level = "s"
