[workspace]
resolver = "2"
members = ["tauri", "boa_utils", "nyanpasu-macro", "nyanpasu-egui"]

[workspace.package]
repository = "https://github.com/keiko233/clash-nyanpasu.git"
edition = "2024"
license = "GPL-3.0"
authors = ["zzzgydi", "keiko233"]

[workspace.dependencies]
thiserror = "2"
tracing = "0.1"
boa_engine = { version = "0.20", features = ["annex-b"] }
reqwest = { version = "0.12", default-features = false, features = [
  "charset",
  "http2",
  "system-proxy",
  "json",
  "stream",
  "rustls-tls",
] }
tokio = { version = "1", features = ["full"] }
nyanpasu-utils = { git = "https://github.com/libnyanpasu/nyanpasu-utils.git", features = [
  "specta",
] }

[profile.release]
panic = "unwind"
codegen-units = 1
lto = true
opt-level = "s"
