[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:edge"
pre-build = [
  "dpkg --add-architecture $CROSS_DEB_ARCH",
  """apt-get update && apt-get -y install \
    libwebkit2gtk-4.1-dev:$CROSS_DEB_ARCH \
    libxdo-dev:$CROSS_DEB_ARCH \
    libayatana-appindicator3-dev:$CROSS_DEB_ARCH \
    librsvg2-dev:$CROSS_DEB_ARCH \
    libpango1.0-dev:$CROSS_DEB_ARCH \
    libcairo2-dev:$CROSS_DEB_ARCH \
    libatk1.0-dev:$CROSS_DEB_ARCH \
    libsoup2.4-dev:$CROSS_DEB_ARCH \
    libssl-dev:$CROSS_DEB_ARCH
  """,
]
