[package]
name = "nyanpasu-service"
version = "1.4.5"
edition = "2024"
repository = { workspace = true }
license = { workspace = true }
default-run = "nyanpasu-service"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nyanpasu-service-runtime = { path = "../crates/nyanpasu-service-runtime" }
nyanpasu-utils = { path = "../crates/nyanpasu-utils", default-features = false }
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true

[target."cfg(windows)".dependencies]
tokio-util = { workspace = true }
windows-service = "0.8"

[features]
deadlock_detection = ["nyanpasu-service-runtime/deadlock_detection"]
debug = ["nyanpasu-service-runtime/debug"]
hardware-lock-elision = ["nyanpasu-service-runtime/hardware-lock-elision"]
tracing = ["nyanpasu-service-runtime/tracing"]
