name: 'packet drop test'
on:
  workflow_dispatch:
    inputs:
      handshake_no_wait:
        description: 'Handshake no wait mode (y/n)'
        required: false
        default: 'n'
        type: string
jobs:
  run-test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Build test binaries
        run: make test-binary
      - name: Set env
        if: github.event.inputs.handshake_no_wait == 'y'
        run: echo "MIERU_HANDSHAKE_NO_WAIT=1" >> $GITHUB_ENV
      - name: Run packet drop test
        run: sudo -E ./test/deploy/packetdrop/test.sh
