export const userKeys = [
  'auto-check-update', 'auto-hide-window', 'auto-sync-tracker', 'cookie',
  'enable-upnp', 'engine-bin-path', 'engine-max-connection-per-server',
  'favorite-directories', 'hide-app-menu', 'history-directories',
  'keep-seeding', 'keep-window-state', 'last-check-update-time',
  'last-sync-tracker-time', 'locale', 'log-level',
  'new-task-show-downloading', 'no-confirm-before-delete-task',
  'open-at-login', 'protocols', 'proxy', 'resume-all-when-app-launched',
  'run-mode', 'show-progress-bar', 'task-notification', 'theme',
  'tracker-source', 'tray-speedometer', 'tray-theme'
]

export const systemKeys = [
  'all-proxy', 'all-proxy-passwd', 'all-proxy-user',
  'allow-overwrite', 'allow-piece-length-change',
  'always-resume', 'async-dns', 'auto-file-renaming', 'auto-save-interval',
  'bt-detach-seed-only', 'bt-enable-hook-after-hash-check', 'bt-enable-lpd',
  'bt-exclude-tracker', 'bt-external-ip', 'bt-force-encryption',
  'bt-hash-check-seed', 'bt-load-saved-metadata', 'bt-max-open-files',
  'bt-max-peers', 'bt-metadata-only', 'bt-min-crypto-level',
  'bt-prioritize-piece', 'bt-remove-unselected-file',
  'bt-request-peer-speed-limit', 'bt-require-crypto', 'bt-save-metadata',
  'bt-seed-unverified', 'bt-stop-timeout', 'bt-tracker',
  'bt-tracker-connect-timeout', 'bt-tracker-interval', 'bt-tracker-timeout',
  'check-certificate', 'check-integrity',
  'conditional-get', 'connect-timeout', 'content-disposition-default-utf8',
  'continue', 'dir', 'disk-cache', 'download-result',
  'dht-entry-point', 'dht-entry-point6', 'dht-file-path', 'dht-file-path6',
  'dht-listen-port', 'dht-message-timeout',
  'enable-color', 'enable-dht', 'enable-dht6', 'enable-http-keep-alive',
  'enable-http-pipelining', 'enable-mmap', 'enable-peer-exchange',
  'file-allocation', 'follow-metalink', 'follow-torrent',
  'force-save', 'force-sequential',
  'ftp-passwd', 'ftp-proxy', 'ftp-proxy-passwd', 'ftp-proxy-user', 'ftp-user',
  'header', 'http-accept-gzip', 'http-no-cache',
  'http-proxy', 'http-proxy-passwd', 'http-proxy-user',
  'https-proxy', 'https-proxy-passwd', 'https-proxy-user',
  'human-readable', 'index-out',
  'listen-port', 'lowest-speed-limit',
  'max-concurrent-downloads', 'max-connection-per-server',
  'max-download-limit', 'max-file-not-found', 'max-mmap-limit',
  'max-overall-download-limit', 'max-overall-upload-limit',
  'max-resume-failure-tries', 'max-tries', 'max-upload-limit',
  'metalink-base-uri', 'metalink-enable-unique-protocol',
  'metalink-language', 'metalink-location', 'metalink-os',
  'metalink-preferred-protocol', 'metalink-version',
  'min-split-size', 'min-tls-version', 'no-file-allocation-limit',
  'no-netrc', 'no-proxy',
  'out', 'pause', 'pause-metadata', 'peer-agent', 'peer-id-prefix',
  'piece-length', 'proxy-method',
  'referer', 'remote-time', 'remove-control-file', 'reuse-uri',
  'retry-wait', 'rpc-listen-port', 'rpc-max-request-size', 'rpc-save-upload-metadata',
  'rpc-secret', 'rpc-secure',
  'save-session', 'save-session-interval',
  'seed-ratio', 'seed-time', 'select-file', 'server-stat-timeout',
  'socket-recv-buffer-size', 'split', 'stream-piece-selector',
  'summary-interval', 'timeout',
  'upload-limit', 'uri-selector', 'use-head', 'user-agent'
]

export const needRestartKeys = [
  'dht-listen-port', 'hide-app-menu', 'listen-port',
  'rpc-listen-port', 'rpc-secret'
]
