export declare const bytesToSize: (bytes: number, precision?: number) => string;
export declare const extractSpeedUnit: (speed: string) => string;
export declare const calcProgress: (totalLength: number, completedLength: number, decimal?: number) => number;
export declare const calcRatio: (totalLength: number, uploadLength: number) => number;
export declare const timeRemaining: (total: number, completed: number, speed: number) => number;
export declare const timeFormat: (seconds: number, opts?: {
    prefix?: string;
    suffix?: string;
    i18n?: any;
}) => string;
export declare const localeDateTimeFormat: (timestamp: number, locale?: string) => string;
export declare const ellipsis: (str: string, maxLen?: number) => string;
export declare const getFileName: (fullPath: string) => string;
export declare const getFileExtension: (filename: string) => string;
export declare const removeExtensionDot: (ext: string) => string;
export declare const getFileNameFromFile: (file: any) => string;
export declare const getTaskName: (task: any, opts?: any) => string;
export declare const checkTaskIsBT: (task: any) => boolean;
export declare const isMagnetTask: (task: any) => boolean;
export declare const checkTaskIsSeeder: (task: any) => boolean;
export declare const checkTaskTitleIsEmpty: (task: any) => boolean;
export declare const isTorrent: (file: any) => boolean;
export declare const getAsBase64: (file: File, callback: (base64: string) => void) => void;
export declare const getTaskUri: (task: any, withTracker?: boolean) => string;
export declare const buildMagnetLink: (task: any, withTracker?: boolean, btTracker?: string) => string;
export declare const getFileSelection: (files: any[]) => string;
export declare const listTorrentFiles: (files: any[]) => any[];
export declare const mergeTaskResult: (response: any[]) => any[];
export declare const decodeThunderLink: (url: string) => string;
export declare const splitTaskLinks: (links: string) => string[];
export declare const splitTextRows: (text: string) => string[];
export declare const convertCommaToLine: (str: string) => string;
export declare const convertLineToComma: (str: string) => string;
export declare const detectResource: (content: string) => boolean;
export declare const buildFileList: (rawFile: File) => any[];
export declare const needCheckCopyright: (links: string) => boolean;
export declare const isAudioOrVideo: (uri: string) => boolean;
export declare const filterVideoFiles: (files: any[]) => any[];
export declare const filterAudioFiles: (files: any[]) => any[];
export declare const filterImageFiles: (files: any[]) => any[];
export declare const filterDocumentFiles: (files: any[]) => any[];
export declare const formatOptionsForEngine: (options?: Record<string, any>) => Record<string, string>;
export declare const separateConfig: (options?: Record<string, any>) => {
    user: Record<string, any>;
    system: Record<string, any>;
    others: Record<string, any>;
};
export declare const changeKeysCase: (obj: Record<string, any>, caseConverter: (s: string) => string) => Record<string, any>;
export declare const changeKeysToCamelCase: (obj: Record<string, any>) => Record<string, any>;
export declare const changeKeysToKebabCase: (obj: Record<string, any>) => Record<string, any>;
export declare const compactUndefined: <T>(arr: (T | undefined)[]) => T[];
export declare const checkIsNeedRestart: (changed: Record<string, any>) => boolean;
export declare const checkIsNeedRun: (enable: boolean, lastTime: number, interval: number) => boolean;
export declare const parseHeader: (header: string) => Record<string, string>;
export declare const buildRpcUrl: ({ port, secret }: {
    port: number;
    secret?: string;
}) => string;
export declare const generateRandomInt: (min: number, max: number) => number;
export declare const intersection: <T>(a1: T[], a2: T[]) => T[];
export declare const cloneArray: <T>(arr: T[], reversed?: boolean) => T[];
export declare const pushItemToFixedLengthArray: <T>(arr: T[], item: T, maxLen: number) => T[];
export declare const removeArrayItem: <T>(arr: T[], item: T) => T[];
export declare const diffConfig: (current: Record<string, any>, next: Record<string, any>) => Record<string, any>;
export declare const getInverseTheme: (theme: string) => string;
export declare const calcFormLabelWidth: (locale: string) => string;
export declare const isRTL: (locale: string) => boolean;
export declare const getLangDirection: (locale: string) => "rtl" | "ltr";
export declare const bitfieldToPercent: (text: string) => number;
export declare const bitfieldToGraphic: (text: string) => string;
export declare const changedConfig: {
    basic: Record<string, any>;
    advanced: Record<string, any>;
};
export declare const backupConfig: {
    theme: string | undefined;
    locale: string | undefined;
};
