export interface IMusicTrack {
  id: string
  source_id?: string
  source_ids?: string[]
  user_id: string
  drive_id: string
  file_id: string
  parent_file_id: string
  parent_path?: string
  file_name: string
  ext: string
  size: number
  category: string
  thumbnail?: string
  description?: string
  encType?: string
  artist?: string
  title?: string
  album?: string
  cover_url?: string
  duration_ms?: number
  lyric_source?: string
  metadata_source?: string
  metadata_version?: number
  metadata_provider?: string
  metadata_confidence?: number
  artwork_origin?: string
  album_artist?: string
  genre?: string
  track_number?: number
  disc_number?: number
  release_date?: string
  musicbrainz_recording_id?: string
  musicbrainz_release_id?: string
  scanned_at: number
  updated_at?: number
  enriched_at?: number
}
