import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";

const require = createRequire(import.meta.url);
const materialIconsRoot = dirname(require.resolve("@material-design-icons/svg/package.json"));

const ICONS = {
  dashboard: "filled",
  text_snippet: "filled",
  folder: "filled",
  swap_vert: "filled",
  terminal: "filled",
  settings: "filled",
  upload: "outlined",
  download: "outlined",
  cable: "outlined",
  tune: "outlined",
  route: "outlined",
  bug_report: "outlined",
  memory: "outlined",
  speed: "filled",
  unfold_more: "filled",
  sync: "filled",
  schedule: "filled",
  filter_list: "filled",
  save: "filled",
  share: "filled",
  delete: "filled",
  content_copy: "filled",
  pause: "filled",
  play_arrow: "filled",
  network_check: "outlined",
  swap_horiz: "filled",
  hub: "outlined",
  open_in_new: "filled",
  qr_code: "filled",
  stop: "filled",
  logout: "filled",
  warning_amber: "outlined",
  power_settings_new: "filled",
  computer: "filled",
  router: "filled",
  edit: "outlined",
  more_horiz: "filled",
  cloud_off: "outlined",
  search: "filled",
  close: "filled",
  check: "filled",
  add: "filled",
  more_vert: "filled",
  expand_more: "filled",
  expand_less: "filled",
  keyboard_arrow_right: "filled",
  arrow_back: "filled",
  drag_handle: "filled",
  menu: "filled",
  dns: "filled",
  usb: "filled",
  usb_off: "filled",
  description: "outlined",
  code: "outlined",
  brightness_auto: "filled",
  light_mode: "filled",
  dark_mode: "filled",
  language: "filled",
  palette: "filled",
  visibility: "filled",
  visibility_off: "filled",
  favorite: "outlined",
  info: "outlined",
  undo: "filled",
  redo: "filled",
};

const out = ["// Generated by scripts/gen-icons.mjs — do not edit by hand.",
  "// Icon artwork: Material Design Icons (@material-design-icons/svg), Apache-2.0.",
  "export const ICON_PATHS = {"];

for (const [name, style] of Object.entries(ICONS)) {
  const svg = readFileSync(
    join(materialIconsRoot, style, `${name}.svg`),
    "utf8",
  );
  const paths = [...svg.matchAll(/<path([^>]*)\/>/g)]
    .filter(([, attrs]) => !attrs.includes('fill="none"'))
    .map(([, attrs]) => attrs.match(/ d="([^"]+)"/)?.[1])
    .filter(Boolean);
  if (paths.length === 0) throw new Error(`no path data in ${style}/${name}.svg`);
  out.push(`  ${name}: ${JSON.stringify(paths.join(" "))},`);
}

out.push("} as const;", "", "export type IconName = keyof typeof ICON_PATHS;", "");
writeFileSync(new URL("../src/components/iconPaths.ts", import.meta.url), out.join("\n"));
console.log(`wrote ${Object.keys(ICONS).length} icons`);
