version: 2.1

orbs:
  android: circleci/android@2.3.0

jobs:
  build:
    executor:
      name: android/android-docker
      tag: 2024.08.1-ndk
      resource-class: large
    environment:
      GRADLE_OPTS: -Dorg.gradle.workers.max=1 -Dorg.gradle.daemon=false -Dkotlin.compiler.execution.strategy="in-process"
      RUST_VERSION: 1.80.0
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain $RUST_VERSION -y
      - run:
          name: Update environment variables
          command: |
            echo 'export PATH="$HOME"/.cargo/bin:"$PATH"' >> "$BASH_ENV"
      - run: rustup target add armv7-linux-androideabi aarch64-linux-android i686-linux-android x86_64-linux-android
      - android/restore-gradle-cache
      - run:
          name: Run Build and Tests
          command: ./gradlew assembleDebug check -PCARGO_PROFILE=debug
      - android/save-gradle-cache
      - store_artifacts:
          path: mobile/build/outputs/apk
          destination: apk/mobile
      - store_artifacts:
          path: tv/build/outputs/apk
          destination: apk/tv
      - store_artifacts:
          path: core/build/reports
          destination: reports/core
      - store_artifacts:
          path: mobile/build/reports
          destination: reports/mobile
      - store_artifacts:
          path: plugin/build/reports
          destination: reports/plugin
      - store_artifacts:
          path: tv/build/reports
          destination: reports/tv

workflows:
  test:
    jobs:
      - build
