with-expecter: true
dir: .
outpkg: sniff
packages:
  github.com/apernet/quic-go:
    interfaces:
      Stream:
        config:
          mockname: mockStream
          replace-type: # internal package alias dirty fix
            - github.com/apernet/quic-go/internal/protocol=github.com/apernet/quic-go
            - github.com/apernet/quic-go/internal/qerr=github.com/apernet/quic-go
