name: "Publish scripts"

on:
  push:
    branches:
      - master
    paths:
      - scripts/**

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish scripts to Cloudflare Pages
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: hy2scripts
          directory: scripts
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main
