export const PLAN_SCHEMA_VERSION = 1

function field(name, type, description, required = true) {
  return { name, type, required, description }
}

export const PLAN_SCHEMAS = [
  {
    name: 'rename',
    command: 'files rename-apply',
    operation: 'rename',
    destructive: false,
    undoable: true,
    requiresDryRun: true,
    applyRequiresRationale: true,
    description: 'Rename one or more cloud-drive files or folders by file id.',
    fields: [
      field('version', 'number', 'Plan schema version. Must be 1.'),
      field('operation', 'string', 'Operation name. Must be "rename".'),
      field('provider', 'string', 'Cloud-drive provider id.'),
      field('account_id', 'string', 'CLI account id or "default".'),
      field('created_at', 'string', 'ISO timestamp when the plan was created.', false),
      field('items', 'array', 'Non-empty list of rename items.'),
    ],
    itemFields: [
      field('drive_id', 'string', 'Provider drive id.'),
      field('file_id', 'string', 'Target file or folder id.'),
      field('parent_file_id', 'string', 'Current parent folder id.'),
      field('old_name', 'string', 'Expected current name.'),
      field('new_name', 'string', 'Desired new name.'),
      field('reason', 'string', 'Short item-level reason.', false),
    ],
    example: {
      version: 1,
      operation: 'rename',
      provider: 'aliyun',
      account_id: 'default',
      created_at: '2026-07-30T00:00:00.000Z',
      items: [
        {
          drive_id: 'drive',
          file_id: 'file-id-1',
          parent_file_id: 'parent-id',
          old_name: 'old-name.txt',
          new_name: 'new-name.txt',
          reason: 'User requested a clearer filename',
        },
      ],
    },
  },
  {
    name: 'move',
    command: 'files move-apply',
    operation: 'move',
    destructive: false,
    undoable: true,
    requiresDryRun: true,
    applyRequiresRationale: true,
    description: 'Move one or more cloud-drive files or folders to another folder.',
    fields: [
      field('version', 'number', 'Plan schema version. Must be 1.'),
      field('operation', 'string', 'Operation name. Must be "move".'),
      field('provider', 'string', 'Cloud-drive provider id.'),
      field('account_id', 'string', 'CLI account id or "default".'),
      field('created_at', 'string', 'ISO timestamp when the plan was created.', false),
      field('items', 'array', 'Non-empty list of move items.'),
    ],
    itemFields: [
      field('drive_id', 'string', 'Provider drive id.', false),
      field('file_id', 'string', 'Target file or folder id.'),
      field('name', 'string', 'Current item name.'),
      field('type', 'string', 'Item type: "file" or "folder".', false),
      field('from_parent_file_id', 'string', 'Current parent folder id.'),
      field('to_parent_file_id', 'string', 'Destination parent folder id.'),
      field('from_path', 'string', 'Optional source path for providers that use paths.', false),
      field('to_folder_path', 'string', 'Optional destination path for providers that use paths.', false),
      field('reason', 'string', 'Short item-level reason.', false),
    ],
    example: {
      version: 1,
      operation: 'move',
      provider: 'aliyun',
      account_id: 'default',
      created_at: '2026-07-30T00:00:00.000Z',
      items: [
        {
          drive_id: 'drive',
          file_id: 'file-id-1',
          name: 'report.pdf',
          type: 'file',
          from_parent_file_id: 'old-parent-id',
          to_parent_file_id: 'new-parent-id',
          reason: 'User requested moving this file into the project folder',
        },
      ],
    },
  },
  {
    name: 'trash',
    command: 'files trash-apply',
    operation: 'trash',
    destructive: true,
    undoable: false,
    requiresDryRun: true,
    applyRequiresRationale: true,
    description: 'Move cloud-drive files or folders to trash, or delete them when a provider only supports delete.',
    fields: [
      field('version', 'number', 'Plan schema version. Must be 1.'),
      field('operation', 'string', 'Operation name. Must be "trash".'),
      field('provider', 'string', 'Cloud-drive provider id.'),
      field('account_id', 'string', 'CLI account id or "default".'),
      field('created_at', 'string', 'ISO timestamp when the plan was created.', false),
      field('items', 'array', 'Non-empty list of trash/delete items.'),
    ],
    itemFields: [
      field('drive_id', 'string', 'Provider drive id.', false),
      field('file_id', 'string', 'Target file or folder id.'),
      field('name', 'string', 'Current item name.'),
      field('type', 'string', 'Item type: "file" or "folder".', false),
      field('parent_file_id', 'string', 'Current parent folder id.', false),
      field('path', 'string', 'Optional source path for providers that use paths.', false),
      field('reason', 'string', 'Short item-level reason.', false),
    ],
    example: {
      version: 1,
      operation: 'trash',
      provider: 'aliyun',
      account_id: 'default',
      created_at: '2026-07-30T00:00:00.000Z',
      items: [
        {
          drive_id: 'drive',
          file_id: 'file-id-1',
          name: 'obsolete.txt',
          type: 'file',
          parent_file_id: 'parent-id',
          reason: 'User confirmed this file is obsolete',
        },
      ],
    },
  },
  {
    name: 'upload',
    command: 'upload apply',
    operation: 'upload',
    destructive: false,
    undoable: false,
    requiresDryRun: true,
    applyRequiresRationale: true,
    description: 'Upload local files and folders into a cloud-drive folder. Prefer generating this with upload plan.',
    fields: [
      field('version', 'number', 'Plan schema version. Must be 1.'),
      field('operation', 'string', 'Operation name. Must be "upload".'),
      field('provider', 'string', 'Cloud-drive provider id.'),
      field('account_id', 'string', 'CLI account id or "default".'),
      field('created_at', 'string', 'ISO timestamp when the plan was created.', false),
      field('local_root', 'string', 'Absolute local root path.'),
      field('remote_parent_file_id', 'string', 'Destination parent folder id.'),
      field('conflict', 'string', 'Conflict policy. Defaults to "skip".', false),
      field('items', 'array', 'List of local files and folders to upload.'),
    ],
    itemFields: [
      field('type', 'string', 'Item type: "file" or "folder".'),
      field('local_path', 'string', 'Absolute local file path. Required for file items.', false),
      field('relative_path', 'string', 'Path relative to local_root.'),
      field('target_name', 'string', 'Remote target name.'),
      field('size', 'number', 'File size in bytes.', false),
      field('updated_at', 'string', 'Local file modification timestamp.', false),
    ],
    example: {
      version: 1,
      operation: 'upload',
      provider: 'aliyun',
      account_id: 'default',
      created_at: '2026-07-30T00:00:00.000Z',
      local_root: '/absolute/local/folder',
      remote_parent_file_id: 'remote-parent-id',
      conflict: 'skip',
      items: [
        {
          type: 'file',
          local_path: '/absolute/local/folder/report.pdf',
          relative_path: 'report.pdf',
          target_name: 'report.pdf',
          size: 1024,
        },
      ],
    },
  },
]

export function listPlanSchemas({ name } = {}) {
  return name ? PLAN_SCHEMAS.filter((schema) => schema.name === name || schema.operation === name) : PLAN_SCHEMAS
}
