import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

const readSource = (path: string) => readFileSync(resolve(process.cwd(), path), 'utf8')

describe('media acquisition skill loop', () => {
  it('keeps the mediary-style on-demand skill manual without read gates', () => {
    const workflow = readSource('src/services/mediaAcquisition/workflowRunner.ts')
    const acquisitionAgent = readSource('src/services/mediaAcquisition/agent.ts')
    const session = readSource('src/services/agent/session.ts')
    const offlineExecutor = readSource('src/services/mediaAcquisition/magnetExecutor.ts')

    expect(workflow).toContain('readSkill: {')
    expect(workflow).toContain("const selectionTools = ['readSkill'")
    expect(workflow).toContain("const organizingTools = ['readSkill'")
    expect(workflow).toContain("'renameSubtitle'")
    expect(workflow).toContain('renameSubtitle: {')
    expect(workflow).toContain('body: MEDIA_ACQUISITION_SANDBOX_SKILLS[args.section]')
    expect(workflow).toContain("alreadyRead: true, instruction: '该章节已读且内容未变化")
    expect(workflow).toContain('toolAllowlist: active ? organizingTools : selectionTools')
    expect(workflow).not.toContain('terminalToolsAfterObservation:')
    expect(workflow).toContain('每轮只调用一个当前必要的工具')
    expect(workflow).toContain('maxToolCallsPerTurn: 1')
    expect(workflow).toContain('snapshotId: z.string().min(1), candidateId: z.string().min(1)')
    expect(workflow).toContain("candidateIds: z.array(z.string().min(1)).min(1).max(12)")
    expect(workflow).toContain('observedCandidateSnapshots.get(args.snapshotId)?.has(candidate.id)')
    expect(workflow).toContain('untrustedContext: { sandboxState: mediaAcquisitionSandboxState(run) }')
    expect(workflow).toContain('maxContextChars: 48_000')
    expect(workflow).toContain("toolName === 'finish' && value.finished === true && !value.error")
    expect(workflow).toContain('maxToolCalls: 60')
    expect(workflow).toContain('return required.some(code => marked.has(code))')
    expect(workflow).toContain("if (isSystemicMediaAcquisitionFailure(message)) return { error: message, systemicBlock: { reason: message } }")
    expect(workflow).toContain('agentStopReason = `网盘账户或配额受阻：${(systemicBlock as Record<string, unknown>).reason}`')
    expect(workflow).toContain('if (isError) return undefined')
    expect(workflow).not.toContain('const matchingCandidates = sandboxCandidates')
    expect(workflow).toContain('SANDBOX_TRANSFER_NOT_CLAIMED')
    expect(workflow).toContain("['transferring', 'imported'].includes(transferred.status)")
    expect(workflow).toContain("return run.candidates.find(item => item.status === 'imported' || item.status === 'transferring')")
    expect(workflow).toContain('await settleSandboxResult(run, await runMediaAcquisitionSandbox(run, candidate, evidence.added))')
    expect(workflow).toContain("mediaHint: run.target.tmdbId ? { tmdbId: run.target.tmdbId")
    expect(workflow).toContain("if (!scanFolderIds.size) throw new Error('媒体已落盘，但无法解析媒体库刮削目录')")
    expect(workflow).toContain('const leaf = await resolveMediaAcquisitionLeafFolder({ ...run.target, seasonNumber })')
    expect(workflow).toContain('for (const folderId of scanFolderIds) await scanIntoMediaLibrary(run, folderId)')
    const mediaScanner = readSource('src/utils/mediaScanner.ts')
    expect(mediaScanner).toContain("(mediaHint?.mediaType === 'tv' || mediaHint?.mediaType === 'anime') && mediaHint.tmdbId")
    expect(mediaScanner).toContain('String(mediaHint.tmdbId)')
    const database = readSource('electron/main/mediaAcquisition/MediaAcquisitionDb.ts')
    expect(database).toContain('t.target_drive_id = ? AND t.target_parent_file_id = ?')
    expect(database).toContain("existingStatus === 'completed' || existingStatus === 'partial'")
    expect(database).toContain('target_parent_file_id FROM media_acquisition_runs')
    expect(database).toContain('`${mediaKey}:${targetUserId}:${targetDriveId}:${targetParentFileId}`')
    expect(workflow).not.toContain('decisionSnapshotId')
    expect(workflow).not.toContain('candidateIdSchema')
    expect(workflow).not.toContain('getMediaAcquisitionAgentSession')
    expect(workflow).not.toContain('saveMediaAcquisitionAgentSession')
    expect(workflow).toContain('An empty snapshot still enters the sandbox')
    expect(acquisitionAgent).toContain('标题和年份将由 Agent 在已观察快照中判断')
    expect(acquisitionAgent).not.toContain('isMediaAcquisitionCandidateTitleMatched')
    expect(acquisitionAgent).not.toContain('isMediaAcquisitionCandidateYearCompatible')
    expect(acquisitionAgent).toContain('isMediaAcquisitionCandidateSupported')
    expect(workflow).toContain('isMediaAcquisitionCandidateSupported(run.target.targetPlatform, capability, candidate)')
    expect(workflow).toContain('const leaf = await resolveMediaAcquisitionLeafFolder(run.target)')
    expect(workflow).toContain("if (!leaf) return false")
    expect(offlineExecutor).toContain('DownDAL.aTrackDrive115OfflineDownload')
    expect(offlineExecutor).toContain('DownDAL.aTrackCloud123OfflineDownload')
    expect(offlineExecutor).toContain('DownDAL.aTrackPikPakOfflineDownload')
    expect(offlineExecutor).toContain('DownDAL.aTrackGuangyaOfflineDownload')
    expect(workflow).toContain('网盘任务仅落盘了非媒体文件')
    expect(workflow).toContain("const searchSummary = latestRun.events.filter(event => event.phase === 'search').slice(-8).map(event => event.message)")
    expect(workflow).not.toContain('searchEvents,')
    expect(workflow).toContain('import.meta.hot.dispose(() => stopMediaAcquisitionWorkflowRunner())')
    expect(workflow).not.toContain('首次行动必须调用 readSkill')
    expect(workflow).not.toContain('请先调用 readSkill')
    expect(workflow).not.toContain("readSkillSections.has('organize') || !targetVerified")
    expect(workflow).not.toContain('automaticCandidateFallback')
    expect(workflow).toContain('mediaAcquisitionAgentCandidateView(run, candidate)')
    expect(workflow).not.toContain('title: candidate.title, detail: candidate.detail')
    expect(session).toContain('if (!repeatedToolCallExemptions.has(event.toolName))')
    expect(session).toContain('let expectedStop = false')
    expect(session).toContain('if (!expectedStop && agent.state.errorMessage)')
    expect(workflow).not.toContain("repeatedToolCallExemptions: ['readSkill']")
  })
})
