import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

describe('media-library ticket regressions', () => {
  it('keeps local scan media associated with its persisted source and batches storage writes', () => {
    const source = readFileSync(resolve(process.cwd(), 'src/utils/mediaScanner.ts'), 'utf8')
    const storeSource = readFileSync(resolve(process.cwd(), 'src/store/medialibrary.ts'), 'utf8')
    const bookScannerSource = readFileSync(resolve(process.cwd(), 'src/utils/bookScanner.ts'), 'utf8')
    const musicScannerSource = readFileSync(resolve(process.cwd(), 'src/utils/musicScanner.ts'), 'utf8')
    const providerListSource = readFileSync(resolve(process.cwd(), 'src/utils/providerFolderList.ts'), 'utf8')
    const aliDirListSource = readFileSync(resolve(process.cwd(), 'src/aliapi/dirfilelist.ts'), 'utf8')
    const mediaDetailSource = readFileSync(resolve(process.cwd(), 'src/components/MediaDetail.vue'), 'utf8')
    const mediaDbSource = readFileSync(resolve(process.cwd(), 'src/utils/db.ts'), 'utf8')

    expect(source).toContain('this.processVideoBatchWithTransientRetry(currentBatch, folderName, sourceId)')
    expect(source).toContain('this.addUnmatchedMediaItem(file, folderName, sourceId)')
    expect(source).toContain('this.addRetryPendingMediaItem(file, folderName, sourceId)')
    expect(source).toContain('this.mediaStore.beginPersistenceBatch()')
    expect(source).toContain('this.mediaStore.endPersistenceBatch()')
    expect(storeSource).toContain('const beginPersistenceBatch')
    expect(storeSource).toContain('const checkpointPersistenceBatch')
    expect(storeSource).toContain('const endPersistenceBatch')
    expect(storeSource).toContain('stopPersistenceWatchers()')
    expect(storeSource).toContain('const dirtyMediaItems')
    expect(storeSource).toContain('DB.upsertMediaLibraryItems(itemUpserts)')
    expect(storeSource).toContain('DB.deleteMediaLibraryItems(itemDeletes)')
    expect(storeSource).toContain('MEDIA_LIBRARY_DEXIE_MIGRATION_KEY')
    expect(storeSource).toContain('mergeNewestById')
    expect(storeSource).toContain('localStorage.setItem(MEDIA_LIBRARY_DEXIE_MIGRATION_KEY, \'1\')')
    expect(storeSource).toContain('mediaItems.value.push(item)')
    expect(source).toContain('PERSISTENCE_CHECKPOINT_ITEMS = 100')
    expect(source).toContain('PERSISTENCE_CHECKPOINT_MS = 3000')
    expect(source).toContain('iterateLocalVideoFiles')
    expect(source).not.toContain('collectLocalVideoFiles')
    expect(source).toContain('getScopedFolderKey')
    expect(source).toContain('iterateProviderFolderPages')
    expect(bookScannerSource).toContain('iterateProviderFolderPages')
    expect(bookScannerSource).toContain('listWebDavDirectory')
    expect(bookScannerSource).toContain("token.tokenfrom === 'webdav'")
    expect(musicScannerSource).toContain('iterateProviderFolderPages')
    expect(source).toContain('ApiDirFileListPages')
    expect(bookScannerSource).toContain('ApiDirFileListPages')
    expect(musicScannerSource).toContain('ApiDirFileListPages')
    expect(aliDirListSource).toContain('static async *ApiDirFileListPages')
    expect(providerListSource).toContain("import { listProviderItems } from '../drive/providerList'")
    expect(providerListSource).toContain("import { iterateProviderPages } from '../drive/providerPagination'")
    expect(providerListSource).toContain('skipThumbnailHydration: true')
    expect(source).toContain('belongs_to_collection')
    expect(source).toContain('collection_${collection.id}')
    expect(source).toContain('const collectionId = mediaInfo.collectionId')
    expect(mediaDetailSource).toContain('handleCollectionMovieSelect')
    expect(mediaDetailSource).toContain('props.mediaItem.collectionMovies')
    expect(mediaDbSource).toContain('const mergedItems = items.map')
    expect(mediaDbSource).toContain('existing.collectionMovies')
  })
})
