import { describe, expect, it } from 'vitest'
import { existsSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'

function readComponent(path: string) {
  return readFileSync(resolve(process.cwd(), path), 'utf8')
}

describe('Mineradio music UI shell', () => {
  it('tracks remaining Mineradio parity work in a dedicated plan', () => {
    const plan = readComponent('docs/plans/mineradio-remaining-alignment.md')

    expect(plan).toContain('Mineradio Remaining Alignment Implementation Plan')
    expect(plan).toContain('FX panel is not yet full Mineradio parity')
    expect(plan).toContain('P1: FX Panel Full-Parity Pass')
    expect(plan).toContain('P2: Shelf 1:1 Interaction Pass')
    expect(plan).toContain('P4: Desktop Lyrics Window')
    expect(plan).toContain('NetEase/QQ login')
    expect(plan).toContain('User-imported podcast links may be stored as subscriptions')
  })

  it('keeps an obvious additive particle stage', () => {
    const stage = readComponent('src/layout/music/MusicImmersiveStage.vue')
    const stageLyrics = readComponent('src/utils/mineradio/StageLyrics.ts')

    expect(stage).toContain('createParticleField')
    expect(stage).toContain('buildCoverParticleGeometry')
    expect(stage).toContain('coverParticleGridForSize')
    expect(stage).toContain('createCoverMaterial')
    expect(stage).toContain('THREE.ShaderMaterial')
    expect(stage).toContain('THREE.AdditiveBlending')
    expect(stage).toContain('bloomParticles')
    expect(stage).toContain('glowField')
    expect(stage).toContain('nearField')
    expect(stage).toContain('getAudioAnalyser')
    expect(stage).toContain('beatPulse')
    expect(stage).toContain('beatMap?: OfflineBeatMap | null')
    expect(stage).toContain('readOfflineBeatPulse')
    expect(stage).toContain('props.beatMap')
    expect(stage).toContain('map?.peakTimes')
    expect(stage).toContain('map?.cameraBeats')
    expect(stage).toContain('map?.pulseBeats')
    expect(stage).toContain('event?.impact')
    expect(stage).toContain("event?.combo === 'downbeat'")
    expect(stage).toContain('event?.sharpness')
    expect(stage).toContain('props.currentTime')
    expect(stage).toContain('offlineBeatPulse')
    expect(stage).toContain('offlineBeatIndex')
    expect(stage).toContain('lastOfflineHitIndex')
    expect(stage).toContain('radiusKick: beatState.cam.radiusKick + 0.16 * impact')
    expect(stage).toContain('thetaKick: beatState.cam.thetaKick +')
    expect(stage).toContain('scene.add(stageLyrics.group)')
    expect(stage).toContain('syncStageLyric')
    expect(stage).toContain('updateCurrentProgress')
    expect(stage).toContain('shelfMgr.setConfig')
    expect(stage).toContain('shelfMgr.onCardClick')
    expect(stage).toContain('shelfMgr.onTrackClick')
    expect(stage).toContain('shelfMgr.onTrackNext')
    expect(stage).toContain('shelfMgr.onBoundaryScroll')
    expect(stage).toContain('props.onShelfBoundaryScroll?.(direction) || false')
    expect(stage).toContain('shelfMgr.onCenterChange')
    expect(stage).toContain('shelfCenterCard')
    expect(stage).toContain('shelfCenterIndex')
    expect(stage).toContain('shelfCueVisible')
    expect(stage).toContain('music-shelf-detail')
    expect(stage).not.toContain('music-shelf-track-list')
    expect(stage).toContain('@media (max-height: 520px)')
    expect(stage).toContain('playShelfCenterCard')
    expect(stage).toContain("'shelf-card-click'")
    expect(stage).toContain("'shelf-track-click'")
    expect(stage).toContain("'shelf-track-next'")
    expect(stage).toContain('shelfMgr.raycast')
    expect(stage).toContain('shelfMgr.click')
    expect(stage).toContain('isShelfWheelZone')
    expect(stage).toContain('handleWheel')
    expect(stage).toContain("parent.addEventListener('wheel', handleWheel, { passive: false })")
    expect(stage).toContain("window.addEventListener('keydown', handleShelfKeydown, true)")
    expect(stage).toContain("e.code === 'BracketRight' || e.code === 'PageDown'")
    expect(stage).toContain("e.code === 'BracketLeft' || e.code === 'PageUp'")
    expect(stage).toContain('shelfMgr.next()')
    expect(stage).toContain('shelfMgr.prev()')
    expect(stage).toContain('isTypingTarget(e.target)')
    expect(stage).toContain('shelfMgr.scroll(e.deltaY)')
    expect(stage).toContain('shelfMode')
    expect(stage).toContain('customBackgroundUrl')
    expect(stage).toContain('music-stage-bg-video')
    expect(stage).toContain('backgroundOpacity')
    expect(stage).toContain('lastScrolledLyric')
    expect(stage).toContain('scrollActiveLine(false)')
    expect(stage).not.toContain('stageLyrics.show(props.title')
    expect(stage).toContain('pointermove')
    expect(stage).toContain('pointer-events: none')
    expect(stage).not.toContain('music-cover-shell')
    expect(stage).toContain('shelfDetailExpanded')
    expect(stage).toContain('shouldShowShelfDetail')
    expect(stage).toContain('!shelfContentVisible.value')
    expect(stage).toContain("fx.value.shelfPresence === 'always' || shelfDetailExpanded.value")
    expect(stage).toContain('function updateShelfHover')
    expect(stage).toContain('updateShelfHover(pointerInfo)')
    expect(stage).toContain('const hit = pointerInfo ? shelfHitFromPointer(pointerInfo) : shelfHitAt(pointerTarget.x, pointerTarget.y)')
    expect(stage).not.toContain('if (hit >= 0) revealShelfDetail(true)')
    expect(stage).toContain("if (vis.shelfPresence === 'always') return false")
    expect(stage).toContain('function shelfHitFromPointer')
    expect(stage).toContain('function shelfContentHitFromPointer')
    expect(stage).toContain('function shelfContentActionFromPointer')
    expect(stage).toContain('shelfMgr.pickAtScreen')
    expect(stage).toContain('shelfMgr.pickContentAtScreen')
    expect(stage).toContain('shelfMgr.pickContentActionAtScreen')
    expect(stage).toContain('shelfMgr.pickContentPanelAtScreen')
    expect(stage).toContain('shelfMgr.clickContentRow(contentAction.index, contentAction.action)')
    expect(stage).toContain('shelfMgr.hasOpenContent()')
    expect(stage).toContain('shelfMgr.scrollContent(e.deltaY)')
    expect(stage).toContain('function isShelfContentWheelZone')
    expect(stage).toContain('if (shelfContentHitFromPointer(pointerInfo) >= 0) return true')
    expect(stage).toContain('if (shelfContentPanelFromPointer(pointerInfo)) return true')
    expect(stage).toContain("if (vis.shelfMode === 'stage') return pointerInfo.relY > pointerInfo.height * 0.52")
    expect(stage).toContain('function isShelfPreviewZone')
    expect(stage).toContain('function isShelfAutoFocusZone')
    expect(stage).toContain('Math.min(132, Math.max(92, pointerInfo.width * 0.08))')
    expect(stage).not.toContain('Math.min(360, Math.max(148, pointerInfo.width * 0.18))')
    expect(stage).toContain("vis.shelfMode !== 'side' || vis.shelfPresence !== 'auto'")
    expect(stage).toContain('shelfMgr.setHovered(preview ? shelfMgr.getCenterIdx() : hit)')
    expect(stage).toContain('if (pointerInfo && isShelfPreviewZone(pointerInfo))')
    expect(stage).toContain('music-shelf-cue')
    expect(stage).toContain('revealShelfDetail(true)')
    expect(stage).toContain("shelfDetailExpanded ? 'expanded' : 'compact'")
    expect(stage).toContain('visualFx')
    expect(stage).toContain('coverResolution')
    expect(stage).toContain('visual.bloomEnabled')
    expect(stage).toContain('vis.cinemaEnabled')
    expect(stage).toContain('vis.floatLayerEnabled')
    expect(stage).toContain('vis.renderQuality')
    expect(stage).toContain('shelfPresence')
    expect(stage).toContain('shelfOffsetX')
    expect(stage).toContain('shelfOffsetY')
    expect(stage).toContain('shelfOffsetZ')
    expect(stage).toContain('shelfAngleY')
    expect(stage).toContain('shelfBgOpacity')
    expect(stage).toContain('shelfAccentColor')
    expect(stage).toContain('fx.lyricGlowEnabled')
    expect(stage).toContain('visual.beatGlowEnabled')
    expect(stage).toContain('visual.edgeHighlightEnabled')
    expect(stage).toContain('visual.backCoverEnabled')
    expect(stage).toContain('stageLyrics.group.position.set')
    expect(stage).toContain('stageLyrics.group.rotation.set')
    expect(stage).toContain('visual.lyricOffsetX')
    expect(stage).toContain('visual.lyricRotateY')
    expect(stage).toContain('lyric-glow-off')
    expect(stage).toContain('lyricStageStyle')
    expect(stage).toContain('syncStageLyricConfig')
    expect(stage).toContain('stageLyrics.config.fontSize')
    expect(stage).toContain('stageLyrics.shelfDetailMix = shelfDetailLyricMix')
    expect(stage).toContain("stageLyrics.shelfDetailProfile = vis.skullPresetEnabled ? 'skull' : 'normal'")
    expect(stage).toContain('const shelfAvoidX = visual.shelfMode ===')
    expect(stage).toContain('-5.70 * shelfDetailLyricMix')
    expect(stage).toContain('field.position.x += (shelfAvoidX - field.position.x) * 0.10')
    expect(stage).toContain('const hasShelfContent = shelfMgr.hasVisibleContent()')
    expect(stage).toContain('shelfContentVisible.value !== hasShelfContent')
    expect(stage).toContain('shelfDetailLyricMix += ((hasShelfContent ? 1 : 0) - shelfDetailLyricMix) * 0.12')
    expect(stage).toContain('shelf-detail-active')
    expect(stage).toContain('.music-stage.shelf-side.shelf-detail-active .music-stage-copy')
    expect(stage).toContain('shelfMgr.hasVisibleContent()')
    expect(stage).toContain('stageLyrics.config.highlightColor')
    expect(stage).toContain('createSkullPreset')
    expect(stage).toContain('skullPresetEnabled')
    expect(stageLyrics).toContain("type ShelfDetailProfile = 'normal' | 'skull'")
    expect(stageLyrics).toContain('SHELF_DETAIL_PROFILES')
    expect(stageLyrics).toContain("skull: { text: 0.3, glow: 0.12, readability: 0.3, order: 20 }")
    expect(stageLyrics).toContain('detailProfile.order + 2')
    expect(stage).toContain('performanceManagerEnabled')
    expect(stage).toContain('getRenderPixelRatio')
    expect(stage).toContain('getParticleDensityScale')
    expect(stage).toContain('skullField.visible')
    expect(stage).toContain('--music-lyric-letter-spacing')
    expect(stage).toContain("'--music-lyric-letter-spacing': `${visual.lyricLetterSpacing}em`")
    expect(stage).toContain('--music-lyric-glow')
    expect(stage).toContain('ResizeObserver')
    expect(stage).toContain('prefers-reduced-motion')
    expect(stage).toContain('top: calc(100% - clamp(176px, 20vh, 216px))')
    expect(stage).not.toContain('top: calc(50% + min(164px, 22vh))')

    const shelf = readComponent('src/utils/mineradio/ShelfManager.ts')
    expect(shelf).toContain('applyGeneratedTexture')
    expect(shelf).toContain('generated:${mesh.card.id}')
    expect(shelf).toContain('const SHELF_CARD_WIDTH = 2.05')
    expect(shelf).toContain('const SHELF_CARD_HEIGHT = 1.025')
    expect(shelf).toContain('new THREE.PlaneGeometry(w, h)')
    expect(shelf).toContain('reflectionPlane')
    expect(shelf).toContain('reflectionPlane.scale.y = -0.62')
    expect(shelf).toContain('sheenPlane')
    expect(shelf).toContain('makeCardSheenTexture')
    expect(shelf).toContain('sweep.addColorStop(0.42')
    expect(shelf).toContain('m.sheenPlane.material')
    expect(shelf).toContain("m.reflectionPlane.visible = this.config.mode === 'stage'")
    expect(shelf).toContain('reflectionMaterial.map = texture')
    expect(shelf).toContain('canvas.width = 720')
    expect(shelf).toContain('canvas.height = 360')
    expect(shelf).toContain('applyCardCanvasTexture')
    expect(shelf).toContain('roundRect(ctx')
    expect(shelf).toContain('connectorLines')
    expect(shelf).toContain('connectorParticles')
    expect(shelf).toContain('flowPhase')
    expect(shelf).toContain('floorMirror')
    expect(shelf).toContain('contentGroup')
    expect(shelf).toContain('contentRows')
    expect(shelf).toContain('contentClose')
    expect(shelf).toContain('contentAlpha')
    expect(shelf).toContain('contentTargetAlpha')
    expect(shelf).toContain('contentAnchorIndex')
    expect(shelf).toContain('hoveredContentIndex')
    expect(shelf).toContain('setHoveredContent(index')
    expect(shelf).toContain("type ContentRowAction = 'play' | 'next' | 'collect'")
    expect(shelf).toContain('onTrackNext')
    expect(shelf).toContain('onTrackCollect')
    expect(shelf).toContain('onBoundaryScroll')
    expect(shelf).toContain('this.onBoundaryScroll?.(direction)')
    expect(shelf).toContain('openContent(index')
    expect(shelf).toContain('this.openContent(index)')
    expect(shelf).toContain('this.contentOpenIndex === index')
    expect(shelf).toContain('this.closeContent()')
    expect(shelf).toContain('return hadContent')
    expect(shelf).toContain('hasVisibleContent()')
    expect(shelf).toContain('pickContentAtScreen(camera: THREE.Camera')
    expect(shelf).toContain('pickContentActionAtScreen(camera: THREE.Camera')
    expect(shelf).toContain('pickContentCloseAtScreen(camera: THREE.Camera')
    expect(shelf).toContain('clickContentRow(index')
    expect(shelf).toContain('scrollContent(deltaY')
    expect(shelf).toContain('createContentRow')
    expect(shelf).toContain('createContentCloseControl')
    expect(shelf).toContain("ctx.fillText('BACK'")
    expect(shelf).toContain('updateContentList')
    expect(shelf).toContain('update(dt: number, camera: THREE.Camera)')
    expect(shelf).toContain('this.updateContentList(camera)')
    expect(shelf).toContain("this.config.cameraMode === 'dynamic' && camera")
    expect(shelf).toContain('private dynamicLookHelper = new THREE.Object3D()')
    expect(shelf).toContain('this.dynamicLookHelper.position.copy(m.group.position)')
    expect(shelf).toContain('this.dynamicLookHelper.lookAt(cameraPos.x, m.group.position.y, cameraPos.z)')
    expect(shelf).toContain('m.group.quaternion.slerp(this.dynamicLookHelper.quaternion, 0.16)')
    expect(shelf).toContain('this.contentGroup.quaternion.slerp(camera.quaternion')
    expect(shelf).toContain('this.contentAlpha += (this.contentTargetAlpha - this.contentAlpha) * 0.18')
    expect(shelf).toContain('const ease = Math.sin(clamp01(this.contentAlpha) * Math.PI * 0.5)')
    expect(shelf).toContain('const rowIntro = clamp01(this.contentAlpha * 1.4')
    expect(shelf).toContain('const rowEase = Math.sin(rowIntro * Math.PI * 0.5)')
    expect(shelf).toContain('(1 - rowEase) * (isSide ? 0.42 : -0.26)')
    expect(shelf).toContain('isHovered ? 1.025 : 1')
    expect(shelf).toContain('isHovered ? 8 : 0')
    expect(shelf).toContain('disposeContentRows')
    expect(shelf).toContain('createShelfExtras')
    expect(shelf).toContain('updateShelfExtras')
    expect(shelf).toContain('disposeShelfExtras')
    expect(shelf).toContain('new THREE.LineSegments')
    expect(shelf).toContain('new THREE.Points')
    expect(shelf).toContain('new THREE.PointsMaterial')
    expect(shelf).toContain('new THREE.PlaneGeometry(7.2, 1.9)')
    expect(shelf).toContain('if (index !== centerIndex)')
    expect(shelf).toContain('this.targetScroll = clampRange(index')
    expect(shelf).toContain('this.notifyCenter(index)')
    expect(shelf).toContain('presenceAlpha')
    expect(shelf).toContain("this.config.presence === 'auto'")
    expect(shelf).toContain('this.group.position.x = collapse * 2.2')
    expect(shelf).toContain('lastScrollSfxAt')
    expect(shelf).toContain('playExpandSfx')
    expect(shelf).toContain("ctx.fillText('NEXT'")
    expect(shelf).toContain("relX > 0.93 ? 'play'")
    expect(shelf).toContain("relX > 0.865 ? 'collect'")
    expect(shelf).toContain("relX > 0.79 ? 'next'")
    expect(shelf).toContain('beepCluster')
    expect(shelf).toContain("[780, 0.032, 'square'")
    expect(shelf).toContain("[260, 0.05, 'sawtooth'")
    expect(shelf).toContain("[910, 0.028, 'square'")
    expect(shelf).toContain('this.cards.forEach((c, i) => { c.expanded = i === this.selectedIndex })')
    expect(shelf).toContain('pickAtScreen(camera: THREE.Camera')
    expect(shelf).toContain('card.coverPlane.matrixWorld')
    expect(shelf).toContain('const halfW = SHELF_CARD_WIDTH / 2')
    expect(shelf).toContain('const halfH = SHELF_CARD_HEIGHT / 2')
    expect(shelf).toContain('sx >= minX - pad')
    expect(shelf).toContain('const visibleCards = this.cards')
    expect(shelf).toContain('card.group.visible && card.coverPlane.visible')
    expect(shelf).toContain('return visibleCards[meshIndex]?.index ?? -1')
    expect(shelf).toContain('const delta = i - this.scrollOffset')
    expect(shelf).toContain('const absD = Math.abs(delta)')
    expect(shelf).toContain('m.group.visible = absD <= 5.5')
    expect(shelf).toContain('const distanceOpacity = absD < 0.5 ? 1')
    expect(shelf).toContain('this.config.offsetY - delta * SIDE_CARD_GAP_Y')
    expect(shelf).toContain('new THREE.Vector3(SIDE_DETAIL_VIEWPORT_X, SIDE_DETAIL_VIEWPORT_Y, 0.5).unproject(camera)')
    expect(shelf).toContain('this.contentGroup.position.copy(camera.position).add(viewportDirection.multiplyScalar(SIDE_DETAIL_VIEWPORT_DISTANCE')
    expect(shelf).toContain('this.config.size * (isSide ? SIDE_CONTENT_SCALE : 0.92)')
    expect(shelf).toContain('this.config.offsetX + delta * STAGE_CARD_GAP_X')
    expect(shelf).toContain('const base = 300 + Math.min(360')
    expect(shelf).toContain("[base * 1.42, 0.018, 'triangle'")
  })

  it('keeps a Mineradio-style visual control console', () => {
    const player = readComponent('src/layout/PageMusic.vue')

    expect(player).toContain('control-glass-filter-svg')
    expect(player).toContain('mineradio-control-glass-filter')
    expect(player).not.toContain('music-fx-fab')
    expect(player).not.toContain('music-fx-fab-hide')
    expect(player).not.toContain('fxFabAutoHide')
    expect(player).not.toContain('fx-fab-auto-hide')
    expect(player).not.toContain('fx-fab-peek')
    expect(player).not.toContain('toggleFxFabAutoHide')
    expect(player).toContain(':show-fx-panel="showFxPanel"')
    expect(player).toContain('@toggle-fx="showFxPanel = !showFxPanel"')
    expect(player).not.toContain('thumb-wrap')
    expect(player).not.toContain('thumb-cover')
    expect(player).toContain('desktopLyricsOn')
    expect(player).toContain('toggleDesktopLyrics')
    expect(player).toContain('syncDesktopLyricsWindow')
    expect(player).toContain('window.WebOpenLyric')
    expect(player).toContain('window.WebSendLyric')
    expect(player).toContain('window.WebCloseLyric')
    expect(player).toContain('desktop-lyric-preview')
    expect(player).toContain('desktopLyricText')
    expect(player).toContain('pm.desktopLyricsOn')
    expect(player).toContain('desktopLyricsClickThrough')
    expect(player).toContain('desktopLyricsLocked')
    expect(player).toContain('desktopLyricFps')
    expect(player).toContain('pm.desktopLyricsClickThrough')
    expect(player).toContain('pm.desktopLyricsLocked')
    expect(player).toContain('pm.desktopLyricFps')
    expect(player).toContain('toggleDesktopLyricsClickThrough')
    expect(player).toContain('toggleDesktopLyricsLock')
    expect(player).toContain('clickThrough: desktopLyricsClickThrough.value')
    expect(player).toContain('locked: desktopLyricsLocked.value')
    expect(player).toContain('fps: desktopLyricFps.value')
    expect(player).toContain('desktopLyricFontSize')
    expect(player).toContain('desktopLyricPrimaryColor')
    expect(player).toContain('desktopLyricSecondaryColor')
    expect(player).toContain('desktopLyricOpacity')
    expect(player).toContain('desktopLyricY')
    expect(player).toContain('desktopLyricBgOpacity')
    expect(player).toContain('desktopLyricShake')
    expect(player).toContain('desktopLyricFontFamily')
    expect(player).toContain('desktopLyricHighlightFollow')
    expect(player).toContain('pm.desktopLyricFontSize')
    expect(player).toContain('pm.desktopLyricPrimaryColor')
    expect(player).toContain('pm.desktopLyricSecondaryColor')
    expect(player).toContain('pm.desktopLyricOpacity')
    expect(player).toContain('pm.desktopLyricY')
    expect(player).toContain('pm.desktopLyricBgOpacity')
    expect(player).toContain('pm.desktopLyricShake')
    expect(player).toContain('pm.desktopLyricFontFamily')
    expect(player).toContain('pm.desktopLyricHighlightFollow')
    expect(player).toContain('fontSize: desktopLyricFontSize.value')
    expect(player).toContain('fontWeight: visualFx.value.lyricWeight')
    expect(player).toContain('letterSpacing: visualFx.value.lyricLetterSpacing')
    expect(player).toContain('lineHeight: visualFx.value.lyricLineHeight')
    expect(player).toContain('lyricScale: visualFx.value.lyricSize')
    expect(player).toContain('primaryColor: desktopLyricPrimaryColor.value')
    expect(player).toContain('opacity: desktopLyricOpacity.value')
    expect(player).toContain('y: desktopLyricY.value')
    expect(player).toContain('backgroundOpacity: desktopLyricBgOpacity.value')
    expect(player).toContain('shake: desktopLyricShake.value')
    expect(player).toContain('fontFamily: desktopLyricFontFamily.value')
    expect(player).toContain('highlightFollow: desktopLyricHighlightFollow.value')
    expect(player).toContain('diySimpleMode')
    expect(player).toContain('pm.diySimpleMode')
    expect(player).toContain('simple-mode')
    expect(player).toContain('music-fx-advanced')
    expect(player).toContain('music-fx-panel')
    expect(player).toContain('music-beat-chip')
    expect(player).toContain('visual-guide-card')
    expect(player).toContain('hotkey-modal')
    expect(player).toContain('visualGuideItems')
    expect(player).toContain('visualGuideIndex')
    expect(player).toContain('visualGuideCurrent')
    expect(player).toContain(':data-guide-step="visualGuideCurrent.spot"')
    expect(player).toContain('visualGuideCurrent.title')
    expect(player).toContain('visualGuideCurrent.text')
    expect(player).toContain('visual-guide-actions')
    expect(player).toContain('hotkeyItems')
    expect(player).toContain('loadHotkeys')
    expect(player).toContain('saveHotkeys')
    expect(player).toContain('hotkeyFromEvent')
    expect(player).toContain('hasHotkeyConflict')
    expect(player).toContain('captureHotkey')
    expect(player).toContain('resetHotkeys')
    expect(player).toContain('hotkey-capture')
    expect(player).toContain('showVisualGuide')
    expect(player).toContain("e.key.toLowerCase() === 'escape'")
    expect(player).toContain('spotlight-guide-mask')
    expect(player).toContain('visual-guide-spotlight')
    expect(player).toContain('showHotkeyModal')
    expect(player).toContain('showBeatModal')
    expect(player).toContain('beat-modal')
    expect(player).toContain('LOCAL BEAT ANALYSIS')
    expect(player).toContain('只分析当前正在播放的网盘或本地音频')
    expect(player).toContain('BP Beat')
    expect(player).toContain('DJ Beat')
    expect(player).toContain('beatAnalyzing')
    expect(player).toContain('beatAnalyzingMode')
    expect(player).toContain('beatAnalysisTimeoutMs')
    expect(player).toContain('beatInfo')
    expect(player).toContain('beatMap')
    expect(player).toContain(':beat-map="beatMap"')
    expect(player).toContain('getCachedBeatMap')
    expect(player).toContain('loadCachedBeatMapForCurrent')
    expect(player).toContain('beatMap.value = { mode: result.mode')
    expect(player).toContain('beatMap.value = null')
    expect(player).toContain('beatChipVisible')
    expect(player).toContain('scheduleBeatChipHide')
    expect(player).toContain('new AbortController')
    expect(player).toContain('controller.abort()')
    expect(player).toContain('节奏分析超过 ${Math.round(timeoutMs / 1000)} 秒，已停止')
    expect(player).toContain('FLAC 可能需要 1-2 分钟')
    expect(player).toContain('beatChipVisible && (beatAnalyzing || beatInfo)')
    expect(player).toContain('analyzeCurrentBeat')
    expect(player).toContain('analyzeAudioElementBeat')
    const beatAnalyzer = readComponent('src/utils/mineradio/BeatAnalyzer.ts')
    expect(beatAnalyzer).toContain('decodeAudioData')
    expect(beatAnalyzer).toContain('signal?: AbortSignal')
    expect(beatAnalyzer).toContain('fetch(audioEl.src, { signal })')
    expect(beatAnalyzer).toContain('decodeAudioDataWithAbort')
    expect(beatAnalyzer).toContain('Promise.race')
    expect(beatAnalyzer).toContain('throwIfAborted(signal)')
    expect(beatAnalyzer).toContain("err.name = 'AbortError'")
    expect(beatAnalyzer).toContain("signal.removeEventListener('abort', onAbort)")
    expect(beatAnalyzer).toContain('getCachedBeatMap')
    expect(beatAnalyzer).toContain('setCachedBeatMap')
    expect(beatAnalyzer).toContain('buildBandEnergy')
    expect(beatAnalyzer).toContain('lowEnergy')
    expect(beatAnalyzer).toContain('hitEnergy')
    expect(beatAnalyzer).toContain('estimateStep')
    expect(beatAnalyzer).toContain('percentile(lowEnergy')
    expect(beatAnalyzer).toContain('mode === \'dj\'')
    expect(beatAnalyzer).toContain('Math.max(0, lowEnergy[i] - prev)')
    expect(beatAnalyzer).toContain('makeBeatEvents')
    expect(beatAnalyzer).toContain('pulseBeats')
    expect(beatAnalyzer).toContain('cameraBeats')
    expect(beatAnalyzer).toContain("combo === 'downbeat'")
    expect(beatAnalyzer).toContain('impact')
    expect(beatAnalyzer).toContain('confidence')
    const stageLyrics = readComponent('src/utils/mineradio/StageLyrics.ts')
    expect(stageLyrics).toContain('this.config.letterSpacing * Math.max(1, size)')
    const beatCache = readComponent('src/utils/mineradio/BeatMapCache.ts')
    expect(beatCache).toContain('beatMapCacheKey')
    expect(beatCache).toContain('getMineradioValue')
    expect(beatCache).toContain('setMineradioValue')
    expect(beatCache).toContain('MineradioBeatEvent')
    expect(beatCache).toContain('pulseBeats?: MineradioBeatEvent[]')
    expect(beatCache).toContain('cameraBeats?: MineradioBeatEvent[]')
    expect(player).toContain('requestAnimationFrame(tick)')
    expect(player).toContain('stopClockLoop')
    expect(player).toContain('lastMetaQueryKey')
    expect(player).toContain('durationSec: duration || undefined')
    expect(player).toContain('curTime.value = next')
    expect(player).toContain('const displayTimeSec = computed(() => seekPreview.value ?? curTime.value)')
    expect(player).toContain('const lyricClockSec = computed(() => Math.max(0, displayTimeSec.value + lyricTimeOffsetSec.value))')
    expect(player).toContain('findActiveLineIndex(lyricLines.value, lyricClockSec.value)')
    expect(player).toContain('const effectiveDur = computed(() => dur.value > 0 ? dur.value : trackDurationSec.value)')
    expect(player).toContain('(displayTimeSec.value / effectiveDur.value) * 100')
    expect(player).toContain('fmtTime(displayTimeSec.value)')
    expect(player).toContain(':duration-text="fmtTime(effectiveDur)"')
    expect(player).toContain('currentTime: displayTimeSec.value')
    expect(player).toContain(':current-time="lyricClockSec"')
    expect(player).toContain('pm.lyricTimeOffset.')
    expect(player).toContain('adjustLyricTimeOffset(-0.1)')
    expect(player).toContain('resetLyricTimeOffset')
    expect(player).toContain('time - lyricTimeOffsetSec.value')
    expect(player).toContain('bottom: 132px')
    expect(player).toContain('@media (max-height: 520px)')
    expect(player).toContain('width: min(340px, calc(100vw - 36px))')
    expect(player).toContain('right: -460px')
    expect(player).toContain('width: min(444px, calc(100vw - 48px))')
    expect(player).toContain('<MusicMiniQueue')
    expect(player).toContain('showQueue')
    expect(player).toContain('@toggle-panel="showPanel = !showPanel; showQueue = false"')
    expect(player).toContain('@next-play="moveQueueNext"')
    expect(player).toContain('@remove-queue="removeQueueAt"')
    expect(player).toContain('function moveQueueNext')
    const library = readComponent('src/layout/PageMusicLibrary.vue')
    expect(library).toContain('duration_ms: t.duration_ms')
    const appstore = readComponent('src/store/appstore.ts')
    expect(appstore).toContain('duration_ms?: number')
    const stage = readComponent('src/layout/music/MusicImmersiveStage.vue')
    expect(stage).toContain("`shelf-${fx.shelfMode}`")
    expect(stage).toContain('.music-stage.shelf-side .music-shelf-detail')
    expect(stage).not.toContain('music-shelf-track-list')
    expect(player).toContain('视觉控制台')
    expect(player).toContain('BOXPLAYER RADIO VISUALS')
    expect(player).toContain('pm.visualFx')
    expect(player).toContain('DEFAULT_MUSIC_FX')
    expect(player).toContain('MUSIC_FX_PRESETS')
    expect(player).toContain('normalizeMusicFxConfig')
    expect(player).toContain('visualFxSlots')
    expect(player).toContain('defaultVisualFxSlots')
    expect(player).toContain('saveVisualFxSlot')
    expect(player).toContain('loadVisualFxSlot')
    expect(player).toContain('pm.visualFxSlots')
    expect(player).toContain('music-fx-user-slots')
    expect(player).toContain('music-fx-slot')
    expect(player).toContain('exportVisualFx')
    expect(player).toContain('importVisualFx')
    expect(player).toContain(':shelf-cards="shelfCards"')
    expect(player).toContain(':on-shelf-boundary-scroll="handleShelfBoundaryScroll"')
    expect(player).toContain('@shelf-card-click="playShelfCard"')
    expect(player).toContain('@shelf-track-click="playShelfTrack"')
    expect(player).toContain('@shelf-track-next="queueShelfTrackNext"')
    expect(player).toContain('@shelf-track-collect="collectShelfTrack"')
    expect(player).toContain('function playShelfCard')
    expect(player).toContain('function playShelfTrack')
    expect(player).toContain('function queueShelfTrackNext')
    expect(player).toContain('function collectShelfTrack')
    expect(player).toContain('function handleShelfBoundaryScroll')
    expect(player).toContain("shelfCollectionPane = ref<'primary' | 'secondary'>('primary')")
    expect(player).toContain("shelfCollectionPane.value = 'secondary'")
    expect(player).toContain("shelfCollectionPane.value = 'primary'")
    expect(player).toContain('collectTargetTrack')
    expect(player).toContain('collectTargetTitle')
    expect(player).toContain('openCollectModal(track')
    expect(player).toContain('moveQueueNext(index)')
    expect(player).toContain("makeCollection('queue'")
    expect(player).toContain("makeCollection('favorite'")
    expect(player).toContain("makeCollection('recent'")
    expect(player).toContain('visualFx.shelfMode')
    expect(player).toContain('visualFx.shelfPresence')
    expect(player).toContain('visualFx.shelfShowFavorites')
    expect(player).toContain('visualFx.shelfShowRecents')
    expect(player).toContain('visualFx.shelfShowPodcasts')
    expect(player).toContain('visualFx.shelfMergeCollections')
    expect(player).toContain('shelfPodcastTracks')
    expect(player).toContain('shelfAlbumCollections')
    expect(player).toContain('shelfArtistCollections')
    expect(player).toContain('activeKey: currentKey.value')
    expect(player).toContain("makeCollection('podcast'")
    expect(player).toContain('localPlaylistCards')
    expect(player).toContain('makeCollection(`local:${list.id}`, list.name')
    expect(player).toContain('...localPlaylistCards')
    expect(player).toContain('primaryCollections')
    expect(player).toContain('secondaryCollections')
    expect(player).toContain('扩展集合')
    expect(player).toContain('主集合')
    expect(player).toContain('albumCards')
    expect(player).toContain('artistCards')
    expect(player).toContain("function setShelfCameraMode(mode: 'static' | 'dynamic')")
    expect(player).toContain("visualFx.value.shelfAngleY = mode === 'static' ? -15 : 0")
    expect(player).toContain('@click="setShelfCameraMode(\'static\')"')
    expect(player).toContain('@click="setShelfCameraMode(\'dynamic\')"')
    expect(player).toContain('visualFx.shelfOffsetX')
    expect(player).toContain('visualFx.shelfOffsetY')
    expect(player).toContain('visualFx.shelfOffsetZ')
    expect(player).toContain('visualFx.shelfAngleY')
    expect(player).toContain('visualFx.shelfBgOpacity')
    expect(player).toContain('visualFx.shelfAccentColor')
    expect(player).toContain('v-model.number="visualFx.shelfSize" max="1.45" min="0.65"')
    expect(player).toContain('v-model.number="visualFx.shelfOffsetX" max="1.2" min="-1.2"')
    expect(player).toContain('v-model.number="visualFx.shelfOffsetY" max="0.9" min="-0.9"')
    expect(player).toContain('v-model.number="visualFx.shelfOffsetZ" max="0.9" min="-0.9"')
    expect(player).toContain('v-model.number="visualFx.shelfAngleY" max="30" min="-30"')
    expect(player).toContain('v-model.number="visualFx.shelfOpacity" max="1" min="0.25"')
    expect(player).toContain('v-model.number="visualFx.shelfBgOpacity" max="0.98" min="0.25"')
    expect(player).toContain('v-model.number="visualFx.lyricSize" max="1.65" min="0.35"')
    expect(player).toContain('v-model.number="visualFx.lyricLineHeight" max="1.35" min="0.86"')
    expect(player).toContain('v-model.number="visualFx.lyricLetterSpacing" max="0.18" min="-0.04" step="0.005"')
    expect(player).toContain('v-model.number="visualFx.lyricWeight" max="900" min="500" step="50"')
    expect(player).toContain('v-model.number="visualFx.lyricOffsetX" max="2" min="-2"')
    expect(player).toContain('v-model.number="visualFx.lyricOffsetY" max="1.35" min="-1.2"')
    expect(player).toContain('v-model.number="visualFx.lyricOffsetZ" max="1.6" min="-1.6"')
    expect(player).toContain('extractCoverPalette')
    expect(player).toContain('coverPalette')
    expect(player).toContain('sampleCoverPalette')
    expect(player).toContain('applyCoverPalette')
    expect(player).toContain('music-fx-color-pick')
    expect(player).toContain('music-fx-swatches')
    expect(player).toContain('自动隐藏')
    expect(player).toContain('常驻')
    expect(player).toContain('显示收藏')
    expect(player).toContain('显示最近')
    expect(player).toContain('显示播客')
    expect(player).toContain('合并滚动')
    expect(player).toContain('收藏到歌单')
    expect(player).toContain('collect-modal')
    expect(player).toContain('collectCurrentToPlaylist')
    expect(player).toContain('collectCurrentToNewPlaylist')
    expect(player).toContain('globalHotkeysEnabled')
    expect(player).toContain('WebConfigureGlobalHotkeys')
    expect(player).toContain('WebOnGlobalHotkey')
    expect(player).toContain('gesture-hud')
    expect(player).toContain('toggleGestureControl')
    expect(player).toContain('直播后台保持')
    expect(player).toContain('封面取色')
    expect(player).toContain('自定义颜色')
    expect(player).toContain('const COLOR_LAB_PRESETS = [')
    expect(player).toContain("label: '冰蓝', color: '#7fd8ff'")
    expect(player).toContain("label: '日冕', color: '#fff0b8'")
    expect(player).toContain("v-for=\"preset in COLOR_LAB_PRESETS\"")
    expect(player).toContain("--lab-color': preset.color")
    expect(player).toContain('界面高亮')
    expect(player).toContain('视觉主色')
    expect(player).toContain('Home 填充')
    expect(player).toContain('主页图标')
    expect(player).toContain('视觉图标')
    expect(player).toContain('背景颜色')
    expect(player).toContain('visualFx.uiAccentColor')
    expect(player).toContain('visualFx.visualTintColor')
    expect(player).toContain('visualFx.homeAccentColor')
    expect(player).toContain('visualFx.homeIconColor')
    expect(player).toContain('visualFx.visualIconColor')
    expect(player).toContain('visualFx.backgroundColor')
    expect(player).toContain('visualFx.cinemaShake')
    expect(player).toContain('visualFx.lyricGlowStrength')
    expect(player).toContain('visualFx.speed')
    expect(player).toContain('visualFx.colorTension')
    expect(player).toContain('visualFx.bgFade')
    expect(player).toContain('visualFx.lyricGlowParticlesEnabled')
    expect(player).toContain('visualFx.lyricCameraLockEnabled')
    expect(player).toContain('visualFx.wallpaperModeEnabled')
    expect(player).toContain('visualFx.lyricSourceMode')
    expect(player).toContain('visualFx.lyricFontFamily')
    expect(player).toContain('歌词光粒')
    expect(player).toContain('歌词镜头绑定')
    expect(player).toContain('壁纸模式')
    expect(player).toContain('运动速度')
    expect(player).toContain('色彩张力')
    expect(player).toContain('背景压暗')
    expect(player).toContain('歌词来源')
    expect(player).toContain('自定义')
    expect(player).toContain('歌词字体')
    expect(player).toContain('等宽')
    expect(player).toContain('节拍分析')
    expect(player).toContain('视觉引导')
    expect(player).toContain('热键设置')
    expect(player).toContain('桌面歌词')
    expect(player).toContain('桌面字号')
    expect(player).toContain('无上限')
    expect(player).toContain('背景透明')
    expect(player).toContain('电影震动')
    expect(player).toContain('高亮跟随')
    expect(player).toContain('点击穿透')
    expect(player).toContain('简约模式')
    expect(player).toContain('完整版')
    expect(player).toContain('前后景深')
    expect(player).toContain('侧向角度')
    expect(player).toContain('immersiveMode')
    expect(player).toContain('controlsVisible')
    expect(player).toContain('toggleImmersiveMode')
    expect(player).toContain('music-detail-modal')
    expect(player).toContain('歌曲详情')
    expect(player).toContain('<CustomLyricModal')
    expect(player).toContain('<CoverCropModal')
    expect(player).toContain('pm.customLyric.')
    expect(player).toContain('setMineradioValue')
    expect(player).toContain('getMineradioValue')
    expect(player).toContain('customCoverStorageKey')
    expect(player).toContain('customBackgroundStorageKey')
    expect(player).toContain('pickCustomBackground')
    expect(player).toContain('clearCustomBackground')
    expect(player).toContain(':custom-background-url="customBackgroundUrl"')
    expect(player).toContain('clearCustomCover')
    expect(player).toContain('applyCustomLyric')
    expect(player).toContain(':visual-fx="visualFx"')
    expect(player).toContain('resetVisualFx')
    expect(player).toContain('coverResolution')
    expect(player).toContain('背景媒体')
    expect(player).toContain('叠加效果')
    expect(player).toContain('浮空粒子')
    expect(player).toContain('电影镜头')
    expect(player).toContain('粒子溢光')
    expect(player).toContain('歌词溢光')
    expect(player).toContain('性能档位')
    expect(player).toContain('visualFx.floatLayerEnabled')
    expect(player).toContain('visualFx.cinemaEnabled')
    expect(player).toContain('visualFx.bloomEnabled')
    expect(player).toContain('visualFx.lyricGlowEnabled')
    expect(player).toContain('visualFx.beatGlowEnabled')
    expect(player).toContain('visualFx.edgeHighlightEnabled')
    expect(player).toContain('visualFx.backCoverEnabled')
    expect(player).toContain('visualFx.colorLabEnabled')
    expect(player).toContain('visualFx.splashEnabled')
    expect(player).toContain('visualFx.skullPresetEnabled')
    expect(player).toContain('visualFx.performanceManagerEnabled')
    expect(player).toContain('visualFx.glassChromaticOffset')
    expect(player).toContain('visualFx.lyricOffsetX')
    expect(player).toContain('visualFx.lyricOffsetY')
    expect(player).toContain('visualFx.lyricOffsetZ')
    expect(player).toContain('visualFx.lyricRotateX')
    expect(player).toContain('visualFx.lyricRotateY')
    expect(player).toContain('鼓点溢光')
    expect(player).toContain('轮廓高亮')
    expect(player).toContain('背面封面')
    expect(player).toContain('颜色实验室')
    expect(player).toContain('启动动画')
    expect(player).toContain('Skull 预设')
    expect(player).toContain('性能管理')
    expect(player).toContain('mineradio-splash')
    expect(player).toContain('mineradio-splash-noise')
    expect(player).toContain('mineradio-splash-wordmark')
    expect(player).toContain('BoxPlayer')
    expect(player).toContain('Radio')
    expect(player).not.toContain('>Mine<')
    expect(player).toContain('splash-word-mine')
    expect(player).toContain('splash-word-radio')
    expect(player).toContain('mineradio-splash-enter')
    expect(player).toContain('mineradioSplashMine')
    expect(player).toContain('mineradioSplashRadio')
    expect(player).toContain('玻璃色差')
    expect(player).toContain('歌词水平')
    expect(player).toContain('歌词垂直')
    expect(player).toContain('歌词前后')
    expect(player).toContain('上下角度')
    expect(player).toContain('左右角度')
    expect(player).toContain('music-fx-color-lab')
    expect(player).toContain('visualFx.renderQuality')
    expect(player).toContain('歌词外观')
    expect(player).toContain('visualFx.lyricPrimaryColor')
    expect(player).toContain('visualFx.lyricActiveColor')
    expect(player).toContain('visualFx.lyricGlowColor')
    expect(player).toContain('visualFx.lyricSize')
    expect(player).toContain('visualFx.lyricLineHeight')
    expect(player).toContain('visualFx.lyricLetterSpacing')
    expect(player).toContain('visualFx.lyricWeight')
    expect(player).toContain('music-fx-color-row')
    expect(player).toContain('music-fx-toggle-grid')
    expect(player).toContain('music-fx-toggle')
    expect(player).toContain('SoundEffectBtn')
    expect(player).not.toContain('setSleep')
    expect(player).not.toContain('sleepEndTrack')

    const hotkeys = readComponent('src/utils/mineradio/HotkeyConfig.ts')
    expect(hotkeys).toContain('DEFAULT_MINERADIO_HOTKEYS')
    expect(hotkeys).toContain('hotkeyFromEvent')
    expect(hotkeys).toContain('hasHotkeyConflict')
    expect(hotkeys).toContain('saveHotkeys')
    const skull = readComponent('src/utils/mineradio/SkullPreset.ts')
    expect(skull).toContain('createSkullPreset')
    expect(skull).toContain('SKULL_PRESET_ASSET')
    expect(skull).toContain('skull-decimation-points.bin')
    expect(skull).toContain('applySkullPointBuffer')
    expect(skull).toContain('new Float32Array(buffer)')
    expect(skull).toContain('THREE.Points')
    expect(existsSync(resolve(process.cwd(), 'public/assets/@mineradio/skull-decimation-points.bin'))).toBe(true)
    const perf = readComponent('src/utils/mineradio/RenderPerformanceManager.ts')
    expect(perf).toContain('getRenderPixelRatio')
    expect(perf).toContain('getParticleDensityScale')

    const ipc = readComponent('electron/main/core/ipcEvent.ts')
    expect(ipc).toContain('handleWebOpenLyric')
    expect(ipc).toContain('desktop-lyrics.html')
    expect(ipc).toContain('transparent: true')
    expect(ipc).toContain('setIgnoreMouseEvents')
    expect(ipc).toContain('handleWebConfigureGlobalHotkeys')
    expect(ipc).toContain('globalShortcut.register')
    expect(ipc).toContain('WebGlobalHotkey')
    const desktopLyrics = readComponent('public/desktop-lyrics.html')
    expect(desktopLyrics).toContain("ipcRenderer?.on('lyricData'")
    expect(desktopLyrics).toContain('-webkit-app-region: drag')
    expect(desktopLyrics).toContain('--desktop-lyric-size')
    expect(desktopLyrics).toContain('--desktop-lyric-weight')
    expect(desktopLyrics).toContain('--desktop-lyric-letter-spacing')
    expect(desktopLyrics).toContain('--desktop-lyric-line-height')
    expect(desktopLyrics).toContain('--desktop-lyric-scale')
    expect(desktopLyrics).toContain('--desktop-lyric-primary')
    expect(desktopLyrics).toContain('--desktop-lyric-secondary')
    expect(desktopLyrics).toContain('--desktop-lyric-opacity')
    expect(desktopLyrics).toContain('--desktop-lyric-y-offset')
    expect(desktopLyrics).toContain('--desktop-lyric-bg')
    expect(desktopLyrics).toContain('--desktop-lyric-shake')
    expect(desktopLyrics).toContain('--desktop-lyric-font')
    expect(desktopLyrics).toContain("root.classList.toggle('follow'")
    expect(desktopLyrics).toContain("root.classList.toggle('locked'")
    expect(desktopLyrics).toContain('--desktop-lyric-frame')
    expect(desktopLyrics).toContain("Number(data?.y ?? .5)")
    expect(desktopLyrics).toContain("Number(data?.opacity ?? 1)")
    expect(desktopLyrics).toContain('UNLIMITED')
    expect(desktopLyrics).toContain('lyricCinemaShake')
  })

  it('keeps the Mineradio bottom console structure', () => {
    const console = readComponent('src/layout/music/MusicBottomConsole.vue')

    expect(console).toContain('mineradio-bottom-handle')
    expect(console).toContain('mineradio-bottom-bar')
    expect(console).toContain('bottom-bar')
    expect(console).toContain('progress-bar')
    expect(console).toContain('progress-fill')
    expect(console).toContain('progress-thumb')
    expect(console).toContain('controls')
    expect(console).toContain('control-cluster actions')
    expect(console).toContain('control-cluster transport')
    expect(console).toContain('control-cluster modes')
    expect(console).toContain('control-cover')
    expect(console).toContain('control-meta')
    expect(console).toContain('ctrl-btn')
    expect(console).toContain('id="play-btn"')
    expect(console).toContain('id="time-display"')
    expect(console).toContain('id="visual-console-btn"')
    expect(console).toContain('SlidersHorizontal')
    expect(console).toContain("showFxPanel ? 'active' : ''")
    expect(console).toContain("emit('toggle-fx')")
    expect(console).toContain('quality-pill')
    expect(console).toContain('quality-popover')
    expect(console).toContain('quality-option')
    expect(console).toMatch(/control-cluster actions[\s\S]*quality-control[\s\S]*control-cluster transport/)
    const modesTemplate = console.slice(console.indexOf('control-cluster modes'), console.indexOf('statusText'))
    expect(modesTemplate).not.toContain('quality-control')
    expect(console).toContain('volume-popover')
    expect(console).not.toContain('music-console-main')
    expect(console).not.toContain('music-console-cover')
    expect(console).not.toContain('SoundEffectBtn')
    expect(console).not.toContain('se-trigger')
    expect(console).not.toContain('set-sleep')
    expect(console).not.toContain('music-sleep-menu')
    expect(console).toContain('width: min(1120px, calc(100vw - clamp(20px, 5vw, 72px)))')
    expect(console).toContain('grid-template-columns: minmax(0, 1fr) max-content minmax(0, 1fr)')
    expect(console).toContain('width: 52px')
    expect(console).toContain('width: 58px')
    expect(console).toContain('border-radius: 50px')
    expect(console).toContain('@media (max-width: 920px)')
    expect(console).toContain('@media (max-height: 520px)')
    expect(console).toContain('width: min(780px, calc(100vw - 42px))')
    expect(console).toContain('@media (max-height: 420px)')
  })

  it('keeps the playlist panel aligned with Mineradio left-side queue behavior', () => {
    const queue = readComponent('src/layout/music/MusicQueuePanel.vue')

    expect(queue).toContain('playlist-panel')
    expect(queue).toContain('panel-tab')
    expect(queue).toContain('queue-list')
    expect(queue).toContain('queue-item')
    expect(queue).toContain("(e: 'next-play', index: number): void")
    expect(queue).toContain("(e: 'remove-queue', index: number): void")
    expect(queue).toContain("emit('next-play', row.sourceIndex)")
    expect(queue).toContain("emit('remove-queue', row.sourceIndex)")
    expect(queue).toContain('left: -410px')
    expect(queue).toContain('left: 32px')
    expect(queue).toContain('top: 78px')
    expect(queue).toContain('width: 340px')
    expect(queue).toContain('backdrop-filter: blur(34px)')
  })

  it('keeps the 3D shelf interactive and avoids blank grey fallback covers', () => {
    const shelf = readComponent('src/utils/mineradio/ShelfManager.ts')
    const stageLyrics = readComponent('src/utils/mineradio/StageLyrics.ts')
    const stage = readComponent('src/layout/music/MusicImmersiveStage.vue')

    expect(shelf).toContain('onCardClick')
    expect(shelf).toContain('raycast(raycaster')
    expect(shelf).toContain('click(index')
    expect(shelf).toContain('scrollBy(step')
    expect(shelf).toContain('next()')
    expect(shelf).toContain('prev()')
    expect(shelf).toContain('scrollVelocity = 0')
    expect(shelf).toContain('this.targetScroll = clampRange(this.targetScroll + this.scrollVelocity, 0, maxScroll)')
    expect(shelf).toContain('this.scrollVelocity *= 0.84')
    expect(shelf).toContain('const impulse = clampRange(Math.abs(step), 1, 2.4) * direction')
    expect(shelf).toContain('this.scrollVelocity = clampRange(this.scrollVelocity + impulse * 0.18, -0.85, 0.85)')
    expect(shelf).toContain('this.targetScroll = clampRange(this.targetScroll + impulse * 0.46, 0, this.cards.length - 1)')
    expect(shelf).toContain('clampRange(deltaY / 120, -2.4, 2.4)')
    expect(shelf).toContain('getCenterIdx')
    expect(shelf).toContain('onCenterChange')
    expect(shelf).toContain('notifyCenter')
    expect(shelf).toContain('getCenterCard')
    expect(shelf).toContain('this.selectedIndex = Math.round(this.targetScroll)')
    expect(shelf).toContain('visibleCards.map')
    expect(shelf).toContain('(b.card.group.renderOrder || 0) - (a.card.group.renderOrder || 0)')
    expect(shelf).toContain('nextSignature')
    expect(shelf).toContain("`${c.id}|${c.coverUrl || ''}|${c.title || ''}|${c.subtitle || ''}|${c.trackCount || 0}|${c.data?.activeKey || ''}`")
    expect(shelf).toContain('prev.presence !== next.presence')
    expect(shelf).toContain('prev.bgOpacity')
    expect(shelf).toContain('passiveDim')
    expect(shelf).toContain('expandAlpha: 0')
    expect(shelf).toContain('const expandTarget = (m.expanded || (absD < 0.42 && this.contentOpenIndex === i)) ? 1 : 0')
    expect(shelf).toContain('m.expandAlpha += (expandTarget - m.expandAlpha) * 0.16')
    expect(shelf).toContain('m.expandAlpha * 0.24')
    expect(shelf).toContain('m.expandAlpha * 0.26')
    expect(shelf).toContain('const SIDE_SHELF_SAFE_X = 6.00')
    expect(shelf).toContain('const SIDE_DETAIL_CARD_OFFSET_X = -2.15')
    expect(shelf).toContain('const SIDE_CONTENT_SCALE = 0.78')
    expect(shelf).toContain('const SIDE_DETAIL_VIEWPORT_X = 0.34')
    expect(shelf).toContain('const SIDE_DETAIL_VIEWPORT_Y = 0.03')
    expect(shelf).toContain('const SIDE_DETAIL_VIEWPORT_DISTANCE = 11.2')
    expect(shelf).toContain('const SIDE_CARD_GAP_Y = 0.72')
    expect(shelf).toContain('const STAGE_CARD_GAP_X = 1.68')
    expect(shelf).toContain('const detailMode = this.contentOpenIndex >= 0')
    expect(shelf).toContain('const detailCardScale = detailMode ?')
    expect(shelf).toContain('m.group.visible = detailMode ? false : absD <= 5.5')
    expect(shelf).toContain('SIDE_SHELF_SAFE_X + (detailMode ? SIDE_DETAIL_CARD_OFFSET_X : 0) + absD * 0.05 + this.config.offsetX')
    expect(shelf).toContain('this.config.offsetY - delta * SIDE_CARD_GAP_Y')
    expect(shelf).toContain('this.config.offsetX + delta * STAGE_CARD_GAP_X')
    expect(shelf).toContain('this.contentGroup.quaternion.slerp(camera.quaternion, 0.22)')
    expect(shelf).toContain('applyGeneratedTexture')
    expect(shelf).toContain("loader.setCrossOrigin('anonymous')")
    expect(shelf).toContain('composed:${mesh.card.id}:${url}:${this.config.accentColor}')
    expect(shelf).toContain('material.color.set(0xffffff)')
    expect(shelf).toContain('new THREE.CanvasTexture')
    expect(shelf).toContain('mesh.card.title')
    expect(shelf).toContain('mesh.card.subtitle')
    expect(shelf).toContain('m.group.visible = absD <= 5.5')
    expect(shelf).toContain('m.group.renderOrder = 60 + Math.round')
    expect(shelf).toContain('opacity *= distanceOpacity')
    expect(shelf).toContain('visibleCards.length - 1')
    expect(shelf).toContain('this.connectorLines.geometry.setDrawRange')
    expect(shelf).toContain('this.connectorParticles.geometry.setDrawRange')
    expect(shelf).toContain('THREE.MathUtils.lerp(a.x, b.x, t)')
    expect(shelf).toContain("this.floorMirror.visible = this.config.mode === 'stage'")
    expect(shelf).toContain('canvas.width = 1440')
    expect(shelf).toContain('new THREE.PlaneGeometry(5.5, 0.60)')
    expect(shelf).toContain('const halfW = 2.75')
    expect(shelf).toContain('const halfH = 0.30')
    expect(shelf).toContain('private contentBackdrop')
    expect(shelf).toContain('private contentScrollRail')
    expect(shelf).toContain('createContentBackdrop')
    expect(shelf).toContain('createContentScrollRail')
    expect(shelf).toContain('new THREE.PlaneGeometry(5.9, 4.55)')
    expect(shelf).toContain('pickContentPanelAtScreen')
    expect(shelf).toContain('const halfW = 2.95')
    expect(shelf).toContain('const halfH = 2.275')
    expect(shelf).toContain('this.contentBackdrop.material.opacity = 0.86 * ease * this.presenceAlpha')
    expect(shelf).toContain('const progress = clampRange(this.contentScrollOffset / maxScroll, 0, 1)')
    expect(shelf).toContain('this.contentScrollRail.group.position.set(2.34, -0.84, 0.08)')
    expect(shelf).toContain('this.contentScrollRail.thumb.position.y = railSpan * 0.5 - progress * railSpan')
    expect(shelf).toContain('row.group.position.set((1 - rowEase) * (isSide ? 0.42 : -0.26), -0.82 - delta * (isSide ? 0.74 : 0.42)')
    expect(shelf).toContain('this.contentClose.group.position.set(2.00, 1.84, 0.10)')
    expect(shelf).toContain('this.connectorLines.visible = this.contentOpenIndex < 0')
    expect(shelf).toContain('this.connectorParticles.visible = this.contentOpenIndex < 0')
    expect(shelf).toContain('this.contentRows.length')
    expect(shelf).toContain('this.contentTargetScroll = clampRange')
    expect(stageLyrics).toContain('shelfDetailMix = 0')
    expect(stageLyrics).toContain('const detailMix = clamp01(this.shelfDetailMix)')
    expect(stageLyrics).toContain('const detailProfile = SHELF_DETAIL_PROFILES[this.shelfDetailProfile]')
    expect(stageLyrics).toContain('const textAlpha = 1 - detailMix * (1 - detailProfile.text)')
    expect(stageLyrics).toContain('this.group.renderOrder = detailMix > 0.04 ? detailProfile.order : 38')
    expect(stageLyrics).toContain('mesh.textMat.uniforms.uAlpha.value = textAlpha')
    expect(stage).toContain("e.code === 'Escape' && shelfMgr.hasOpenContent()")
    expect(stage).toContain('shelfMgr.update(dt, camera)')
    expect(stage).toContain('shelfContentCloseFromPointer')
    expect(stage).toContain('shelfMgr.pickContentCloseAtScreen')
    expect(stage).toContain('if (shelfMgr.hasOpenContent() && shelfMgr.closeContent())')
    expect(stage).toContain('shelfMgr.setHoveredContent(contentHit)')
    expect(stage).toContain('shelfMgr.setHoveredContent(-1)')
    expect(shelf).not.toContain('if (this.onCardClick) {\n      this.onCardClick(this.cards[index].card)\n    }\n    this.playClickSfx()')
  })

  it('normalizes the Mineradio FX config controls used by the player', () => {
    const fxConfig = readComponent('src/utils/mineradio/FxConfig.ts')

    expect(fxConfig).toContain("export type RenderQuality = 'auto' | 'keep' | 'release'")
    expect(fxConfig).toContain("export type LyricSourceMode = 'original' | 'custom'")
    expect(fxConfig).toContain("export type LyricFontFamily = 'system' | 'serif' | 'gothic' | 'mono'")
    expect(fxConfig).toContain('bloomEnabled: boolean')
    expect(fxConfig).toContain('cinemaEnabled: boolean')
    expect(fxConfig).toContain('floatLayerEnabled: boolean')
    expect(fxConfig).toContain('lyricGlowEnabled: boolean')
    expect(fxConfig).toContain('renderQuality: RenderQuality')
    expect(fxConfig).toContain("export type ShelfPresence = 'auto' | 'always'")
    expect(fxConfig).toContain('shelfPresence: ShelfPresence')
    expect(fxConfig).toContain('shelfOffsetX: number')
    expect(fxConfig).toContain('shelfAngleY: number')
    expect(fxConfig).toContain('shelfBgOpacity: number')
    expect(fxConfig).toContain('shelfAccentColor: string')
    expect(fxConfig).toContain('shelfShowFavorites: boolean')
    expect(fxConfig).toContain('shelfShowRecents: boolean')
    expect(fxConfig).toContain('shelfShowPodcasts: boolean')
    expect(fxConfig).toContain('shelfMergeCollections: boolean')
    expect(fxConfig).toContain('liveBackgroundKeep: boolean')
    expect(fxConfig).toContain('gestureControlEnabled: boolean')
    expect(fxConfig).toContain('lyricPrimaryColor: string')
    expect(fxConfig).toContain('lyricActiveColor: string')
    expect(fxConfig).toContain('lyricGlowColor: string')
    expect(fxConfig).toContain('speed: number')
    expect(fxConfig).toContain('colorTension: number')
    expect(fxConfig).toContain('bgFade: number')
    expect(fxConfig).toContain('cinemaShake: number')
    expect(fxConfig).toContain('lyricGlowStrength: number')
    expect(fxConfig).toContain('uiAccentColor: string')
    expect(fxConfig).toContain('visualTintColor: string')
    expect(fxConfig).toContain('homeAccentColor: string')
    expect(fxConfig).toContain('homeIconColor: string')
    expect(fxConfig).toContain('visualIconColor: string')
    expect(fxConfig).toContain('backgroundColor: string')
    expect(fxConfig).toContain('lyricGlowParticlesEnabled: boolean')
    expect(fxConfig).toContain('lyricCameraLockEnabled: boolean')
    expect(fxConfig).toContain('wallpaperModeEnabled: boolean')
    expect(fxConfig).toContain('lyricSourceMode: LyricSourceMode')
    expect(fxConfig).toContain('lyricFontFamily: LyricFontFamily')
    expect(fxConfig).toContain('lyricLetterSpacing: number')
    expect(fxConfig).toContain('intensity: 0.85')
    expect(fxConfig).toContain('scatter: 0')
    expect(fxConfig).toContain('twist: 0')
    expect(fxConfig).toContain('bloom: 0.62')
    expect(fxConfig).toContain('coverResolution: 1.55')
    expect(fxConfig).toContain("uiAccentColor: '#ffffff'")
    expect(fxConfig).toContain("homeAccentColor: '#ffffff'")
    expect(fxConfig).toContain("visualIconColor: '#ffffff'")
    expect(fxConfig).toContain('bloomEnabled: false')
    expect(fxConfig).toContain('cinemaEnabled: true')
    expect(fxConfig).toContain('floatLayerEnabled: false')
    expect(fxConfig).toContain('lyricGlowEnabled: true')
    expect(fxConfig).toContain("renderQuality: 'auto'")
    expect(fxConfig).toContain("shelfPresence: 'always'")
    expect(fxConfig).toContain('shelfShowFavorites: false')
    expect(fxConfig).toContain('shelfShowRecents: false')
    expect(fxConfig).toContain('shelfShowPodcasts: false')
    expect(fxConfig).toContain('shelfOpacity: 1')
    expect(fxConfig).toContain('shelfBgOpacity: 0.9')
    expect(fxConfig).toContain('shelfMergeCollections: false')
    expect(fxConfig).toContain('numberIn(raw.shelfSize, 0.65, 1.45')
    expect(fxConfig).toContain('numberIn(raw.shelfOffsetX, -1.2, 1.2')
    expect(fxConfig).toContain('numberIn(raw.shelfOffsetY, -0.9, 0.9')
    expect(fxConfig).toContain('numberIn(raw.shelfOffsetZ, -0.9, 0.9')
    expect(fxConfig).toContain('numberIn(raw.shelfAngleY, -30, 30')
    expect(fxConfig).toContain('numberIn(raw.shelfOpacity, 0.25, 1')
    expect(fxConfig).toContain('numberIn(raw.shelfBgOpacity, 0.25, 0.98')
    expect(fxConfig).toContain('numberIn(raw.lyricSize, 0.35, 1.65')
    expect(fxConfig).toContain('numberIn(raw.lyricLineHeight, 0.86, 1.35')
    expect(fxConfig).toContain('numberIn(raw.lyricLetterSpacing, -0.04, 0.18')
    expect(fxConfig).toContain('numberIn(raw.lyricWeight, 500, 900')
    expect(fxConfig).toContain('numberIn(raw.lyricOffsetX, -2, 2')
    expect(fxConfig).toContain('numberIn(raw.lyricOffsetY, -1.2, 1.35')
    expect(fxConfig).toContain('numberIn(raw.lyricOffsetZ, -1.6, 1.6')
    expect(fxConfig).toContain('liveBackgroundKeep: false')
    expect(fxConfig).toContain('gestureControlEnabled: false')
    expect(fxConfig).toContain('splashEnabled: false')
    expect(fxConfig).toContain('skullPresetEnabled: false')
    expect(fxConfig).toContain('performanceManagerEnabled: true')
    expect(fxConfig).toContain("lyricSourceMode: 'original'")
    expect(fxConfig).toContain("lyricFontFamily: 'gothic'")
    expect(fxConfig).toContain("id: 'lyric-lock'")
    expect(fxConfig).toContain("id: 'skull'")
    expect(fxConfig).toContain("id: 'vivid'")
    expect(fxConfig).toContain('name: \'安魂 Skull\'')
    expect(fxConfig).toContain('colorTension: 1.55')
    expect(fxConfig).toContain('shelfPresence(raw.shelfPresence)')
    expect(fxConfig).toContain('boolIn(raw.shelfShowFavorites')
    expect(fxConfig).toContain('boolIn(raw.shelfShowRecents')
    expect(fxConfig).toContain('boolIn(raw.shelfShowPodcasts')
    expect(fxConfig).toContain('boolIn(raw.shelfMergeCollections')
    expect(fxConfig).toContain('boolIn(raw.liveBackgroundKeep')
    expect(fxConfig).toContain('boolIn(raw.gestureControlEnabled')
    expect(fxConfig).toContain('boolIn(raw.splashEnabled')
    expect(fxConfig).toContain('boolIn(raw.skullPresetEnabled')
    expect(fxConfig).toContain('boolIn(raw.performanceManagerEnabled')
    expect(fxConfig).toContain('numberIn(raw.speed')
    expect(fxConfig).toContain('numberIn(raw.colorTension')
    expect(fxConfig).toContain('numberIn(raw.bgFade')
    expect(fxConfig).toContain('numberIn(raw.cinemaShake')
    expect(fxConfig).toContain('numberIn(raw.lyricGlowStrength')
    expect(fxConfig).toContain('colorIn(raw.uiAccentColor')
    expect(fxConfig).toContain('colorIn(raw.visualTintColor')
    expect(fxConfig).toContain('colorIn(raw.backgroundColor')
    expect(fxConfig).toContain('boolIn(raw.lyricGlowParticlesEnabled')
    expect(fxConfig).toContain('boolIn(raw.lyricCameraLockEnabled')
    expect(fxConfig).toContain('boolIn(raw.wallpaperModeEnabled')
    expect(fxConfig).toContain('lyricSourceMode(raw.lyricSourceMode)')
    expect(fxConfig).toContain('lyricFontFamily(raw.lyricFontFamily)')
    expect(fxConfig).toContain('colorIn(raw.shelfAccentColor')
    expect(fxConfig).toContain("lyricFontFamily: 'gothic'")
    expect(fxConfig).toContain('lyricLineHeight: 1')
    expect(fxConfig).toContain('lyricWeight: 900')
    expect(fxConfig).toContain("lyricActiveColor: '#fac900'")
    expect(fxConfig).toContain("lyricGlowColor: '#008aff'")
    expect(fxConfig).toContain('colorIn(raw.lyricGlowColor')
    expect(fxConfig).toContain('boolIn(raw.bloomEnabled')
    expect(fxConfig).toContain('renderQuality(raw.renderQuality)')

    const stage = readComponent('src/layout/music/MusicImmersiveStage.vue')
    expect(stage).toContain('uColorTension')
    expect(stage).toContain('uTint')
    expect(stage).toContain('backCoverParticles')
    expect(stage).toContain('edgeParticles')
    expect(stage).toContain('loadSkullPresetAsset')
    expect(stage).toContain('fetch(SKULL_PRESET_ASSET)')
    expect(stage).toContain('applySkullPointBuffer')
    expect(stage).toContain('vis.speed')
    expect(stage).toContain('vis.cinemaShake')
    expect(stage).toContain('fx.value.bgFade')
    expect(stage).toContain('fx.value.colorTension')
    expect(stage).toContain('colorUniform(visual.visualTintColor)')
    expect(stage).toContain('visual.lyricGlowStrength')
    expect(stage).toContain('visual.lyricGlowParticlesEnabled')
    expect(stage).toContain('vis.lyricCameraLockEnabled')
    expect(stage).toContain('--music-lyric-font')
    expect(stage).toContain('stageBgFilter')
    expect(stage).toContain('cameraLookTarget.copy(stageLyrics.group.position)')
  })

  it('keeps the library home aligned with Mineradio and opens the player in a window', () => {
    const library = readComponent('src/layout/PageMusicLibrary.vue')
    const player = readComponent('src/layout/PageMusic.vue')

    expect(library).toContain('aml-home-hero')
    expect(library).toContain('aml-home-section-panel')
    expect(library).toContain('aml-home-tile-row')
    expect(library).toContain('aml-home-card-grid')
    expect(library).toContain('aml-home-song-list')
    expect(library).toContain('data-home-tone')
    expect(library).toContain('homeTone')
    expect(library).toContain('aml-weather-chip')
    expect(library).toContain('playWeatherRadio')
    expect(library).toContain('getWeatherRadioMood')
    expect(library).toContain('weatherMood.label')
    expect(library).toContain('aml-weather-mood')
    expect(library).toContain('podcastHiddenKeys')
    expect(library).toContain('externalPodcastFeeds')
    expect(library).toContain('toggleContextFolderPodcast')
    expect(library).toContain('updatePodcastProgress')
    expect(library).toContain('Math.floor(progress * group.items.length)')
    expect(library).toContain('normalizeExternalPodcastUrl')
    expect(library).toContain('addExternalPodcastFeed')
    expect(library).toContain('mr.podcast.externalFeeds')
    expect(library).toContain('@add-external="addExternalPodcastFeed"')
    expect(library).toContain('@open-external="openExternalPodcastFeed"')
    expect(library).toContain('@remove-external="removeExternalPodcastFeed"')
    expect(library).toContain('<PodcastPanel')
    expect(library).toContain('<PlaylistManagerPanel')
    expect(library).toContain('@import-local-songs="importLocalSongs"')
    expect(library).toContain('aml-right-panel')
    expect(library).toContain('mineradio-library')
    expect(library).toContain('.aml-grid-view,')
    expect(library).toContain('.aml-all-songs,')
    expect(library).toContain('.aml-fav-songs,')
    expect(library).toContain('.aml-group-detail')
    expect(library).toContain('rgba(244,210,138,.25)')
    expect(library).toContain("WebOpenWindow({ page: 'PageMusic'")
    expect(library).toContain('musicWindowTheme')
    expect(library).not.toContain("theme: 'dark'")
    expect(library).not.toContain("import PageMusic from './PageMusic.vue'")
    expect(player).toContain("makeCollection('queue'")
    expect(player).toContain("makeCollection('favorite'")
    expect(player).toContain("makeCollection('recent'")
    expect(player).toContain('data: { source: id, tracks, activeKey: currentKey.value }')
    expect(player).not.toContain('playlist.value.slice(0, 18)')

    const podcastPanel = readComponent('src/components/mineradio/PodcastPanel.vue')
    expect(podcastPanel).toContain('lastListened')
    expect(podcastPanel).toContain('podcast-last')
    expect(podcastPanel).toContain('continueFolder')
    expect(podcastPanel).toContain('visibleFolders')
    expect(podcastPanel).toContain('podcast-continue-card')
    expect(podcastPanel).toContain('podcast-search')
    expect(podcastPanel).toContain('podcast-bar')
    expect(podcastPanel).toContain('继续收听')
    expect(podcastPanel).toContain('搜索播客文件夹')
    expect(podcastPanel).toContain('ExternalPodcastFeed')
    expect(podcastPanel).toContain('externalFeeds')
    expect(podcastPanel).toContain('addExternalFeed')
    expect(podcastPanel).toContain('自定义播客链接')
    expect(podcastPanel).toContain('RSS 或播客主页链接')
    expect(podcastPanel).toContain("emit('open-external', feed)")
    const trialBanner = readComponent('src/components/mineradio/TrialBanner.vue')
    expect(trialBanner).toContain("nextState = 'empty'")
    expect(trialBanner).toContain("nextState = 'scanning'")
    expect(trialBanner).toContain("nextState = 'scan-complete'")
    expect(trialBanner).toContain("nextState = 'first-play'")
    expect(trialBanner).toContain("emit('import-local-songs')")
    expect(trialBanner).toContain('导入本地')
    expect(trialBanner).not.toContain('订阅')
    expect(trialBanner).not.toContain('付费')
    const weatherService = readComponent('src/utils/mineradio/WeatherService.ts')
    expect(weatherService).toContain('getWeatherRadioMood')
    expect(weatherService).toContain('雨雪柔和电台')
    expect(weatherService).toContain('清晨唤醒电台')
    expect(weatherService).toContain('夜间城市电台')
    expect(weatherService).toContain('晴日精选电台')

    const rail = readComponent('src/layout/music/MusicLibraryRail.vue')
    expect(rail).toContain('music-rail::before')
    expect(rail).toContain('backdrop-filter')
    expect(rail).toContain('flex: 0 0 218px')
    expect(rail).toContain('border-radius: 999px')
    expect(rail).toContain('rgba(0,245,212,.090)')
    expect(rail).toContain('LibraryScanPanel')
    expect(rail).toContain('导入本地歌曲')
    expect(rail).toContain("emit('import-local-songs')")

    const scanPanel = readComponent('src/components/LibraryScanPanel.vue')
    expect(scanPanel).toContain('library-scan-drive-list')
    expect(scanPanel).toContain('library-scan-drive-card')
    expect(scanPanel).toContain('a-dropdown trigger="click"')
    expect(scanPanel).toContain('library-scan-drive-btn')
    expect(library).toContain('function importLocalSongs')
    expect(library).toContain('local_url: URL.createObjectURL(file)')
    expect(player).toContain('if (t.local_url) return t.local_url')
  })

  it('keeps all top-tab pages on the Mineradio background shell', () => {
    const main = readComponent('src/layout/PageMain.vue')

    expect(main).toContain('--app-mineradio-bg')
    expect(main).toContain('#xbybody::before')
    expect(main).toContain('.hidetabs .arco-tabs-pane')
    expect(main).toContain('<DropOverlay')
    expect(main).toContain('handleMineradioFilesDropped')
    expect(main).toContain('.gs-page')
    expect(main).toContain('.book-library')
  })

  it('applies the music rail glass treatment to app sidebars', () => {
    const main = readComponent('src/layout/PageMain.vue')

    expect(main).toContain('--app-sidebar-glass')
    expect(main).toContain('--app-glass-panel')
    expect(main).toContain('.xbyleft')
    expect(main).toContain('.media-library-nav')
    expect(main).toContain('.media-server-sidebar')
    expect(main).toContain('.book-sidebar')
    expect(main).toContain('.settings-sider')
    expect(main).toContain('.rss-sider')
  })

  it('keeps app-wide Mineradio polish on common product UI primitives', () => {
    const main = readComponent('src/layout/PageMain.vue')

    expect(main).toContain('#xbybody .arco-card')
    expect(main).toContain('#xbybody .arco-table')
    expect(main).toContain('#xbybody .arco-input-wrapper')
    expect(main).toContain('#xbybody .arco-btn-primary')
    expect(main).toContain('#xbyhead')
    expect(main).toContain('#xbyfoot')
    expect(main).toContain('prefers-reduced-motion')
    expect(main).toContain('prefers-reduced-transparency')
  })

  it('keeps the non-music pages visually aligned with the Mineradio shell', () => {
    const main = readComponent('src/layout/PageMain.vue')
    const mediaServer = readComponent('src/views/MediaServerWorkspace.vue')
    const rssXiMa = readComponent('src/rss/rssxima/RssXiMa.vue')
    const mediaNav = readComponent('src/components/MediaLibraryNav.vue')
    const mediaLibrary = readComponent('src/views/MediaLibraryView.vue')
    const bookLibrary = readComponent('src/layout/PageBookLibrary.vue')

    expect(main).toContain('#xbybody .workspace-toolbar')
    expect(main).toContain('#xbybody .rightbg')
    expect(main).toContain('#xbybody .book-main')
    expect(mediaServer).toContain('var(--app-mineradio-ink')
    expect(mediaServer).toContain('var(--app-glass-line')
    expect(rssXiMa).not.toContain('linear-gradient(180deg, #f8fbff')
    expect(rssXiMa).toContain('var(--app-mineradio-ink')
    expect(mediaNav).toContain('rgba(14, 16, 20, 0.8)')
    expect(mediaLibrary).toContain('rgba(255, 255, 255, 0.085)')
    expect(bookLibrary).toContain('background: transparent')
    expect(bookLibrary).toContain("body[arco-theme='dark']")
  })

  it('does not force the Mineradio dark shell onto the light theme', () => {
    const main = readComponent('src/layout/PageMain.vue')
    const bookLibrary = readComponent('src/layout/PageBookLibrary.vue')
    const musicLibrary = readComponent('src/layout/PageMusicLibrary.vue')
    const musicRail = readComponent('src/layout/music/MusicLibraryRail.vue')

    expect(main).toContain("body:not([arco-theme='dark']) #xbybody")
    expect(main).toContain("body:not([arco-theme='dark']) #xbyhead")
    expect(main).toContain("body:not([arco-theme='dark']) #xbyfoot")
    expect(main).toContain('#xbyhead2 .arco-menu')
    expect(main).toContain('background: transparent !important')
    expect(main).toContain('background: var(--color-bg-1)')
    expect(main).toContain('color: var(--color-text-1)')
    expect(musicLibrary).toContain("body:not([arco-theme='dark']) .aml")
    expect(musicLibrary).not.toContain(":global(body:not([arco-theme='dark'])) .aml")
    expect(musicRail).toContain("body:not([arco-theme='dark']) .music-rail")
    expect(musicRail).not.toContain(":global(body:not([arco-theme='dark'])) .music-rail")
    expect(bookLibrary).toContain('background: #fff')
    expect(bookLibrary).toContain("body[arco-theme='dark']")
  })

  it('establishes an App-wide Mineradio token + utility layer in global.css', () => {
    const globalCss = readComponent('src/assets/global.css')

    // App-level tokens on dark theme
    expect(globalCss).toContain("--app-mineradio-bg")
    expect(globalCss).toContain("--app-mineradio-ink")
    expect(globalCss).toContain("--app-mineradio-accent")
    expect(globalCss).toContain("--app-mineradio-champagne")
    expect(globalCss).toContain("--app-glass-panel")
    expect(globalCss).toContain("--app-glass-line")
    expect(globalCss).toContain("--app-glass-hover")
    expect(globalCss).toContain("--app-sidebar-glass")
    expect(globalCss).toContain("--app-card-radius")
    expect(globalCss).toContain("--app-pill-radius")

    // Light theme token degradation
    expect(globalCss).toContain("body:not([arco-theme='dark'])")
    expect(globalCss).toContain("background: var(--color-bg-1)")

    // Utility classes
    expect(globalCss).toContain(".mr-glass")
    expect(globalCss).toContain(".mr-search-pill")
    expect(globalCss).toContain(".mr-sidebar")
    expect(globalCss).toContain(".mr-pill-item")
    expect(globalCss).toContain(".mr-accent-btn")
    expect(globalCss).toContain(".mr-scan-card")
    expect(globalCss).toContain(".mr-row")
    expect(globalCss).toContain(".mr-empty-icon")
    expect(globalCss).toContain(".mr-empty-title")
    expect(globalCss).toContain(".mr-empty-sub")
    expect(globalCss).toContain(".mr-eyebrow")

    // Arco component glass overrides
    expect(globalCss).toContain(".arco-dropdown")
    expect(globalCss).toContain(".arco-select-dropdown")
    expect(globalCss).toContain(".arco-popover-popup-content")
    expect(globalCss).toContain("body[arco-theme='dark'] .rightmenu.arco-dropdown")
    expect(globalCss).toContain("body[arco-theme='dark'] .rightmenu .arco-dropdown-option-icon")
    expect(globalCss).toContain("body:not([arco-theme='dark']) .rightmenu.arco-dropdown")
    expect(globalCss).toContain(".arco-modal")
  })

  it('aligns the cloud-drive file rows and toolbar with the Mineradio shell', () => {
    const fileitem = readComponent('src/assets/fileitem.css')
    const globalCss = readComponent('src/assets/global.css')

    // File rows get cyan hover/selected in dark theme
    expect(fileitem).toContain("body[arco-theme='dark'] .fileitem:hover")
    expect(fileitem).toContain("body[arco-theme='dark'] .fileitem.selected")
    expect(fileitem).toContain('rgba(0,245,212')
    expect(fileitem).toContain("body[arco-theme='dark'] .griditem:hover")
    expect(fileitem).toContain("body[arco-theme='dark'] .griditem.selected")

    // Toolbar uses Mineradio accent in dark theme
    expect(globalCss).toContain("body[arco-theme='dark'] .toppanbtn .arco-btn")
    expect(globalCss).toContain("linear-gradient(135deg, var(--app-mineradio-accent")
    expect(globalCss).toContain("body[arco-theme='dark'] .toppanbtn .arco-input-search .arco-input-wrapper")
  })

  it('aligns the global search page with the Mineradio shell', () => {
    const search = readComponent('src/layout/PageGlobalSearch.vue')
    const searchBox = readComponent('src/layout/PanHubSearchBox.vue')

    // Search page dark-theme glass
    expect(search).toContain("body[arco-theme='dark'] .gs-page")
    expect(search).toContain("body[arco-theme='dark'] .gs-page-tabs")
    expect(search).toContain("body[arco-theme='dark'] .gs-page-tab.active")
    expect(search).toContain("body[arco-theme='dark'] .gs-page-search")
    expect(search).toContain("body[arco-theme='dark'] .gs-page-result-item:hover")
    expect(search).toContain("body[arco-theme='dark'] .gs-ms-card")
    expect(search).toContain('rgba(0,245,212')
    expect(search).toContain('var(--app-mineradio-accent')

    // PanHub search box dark-theme glass
    expect(searchBox).toContain("body[arco-theme='dark'] .ph-box")
    expect(searchBox).toContain("body[arco-theme='dark'] .ph-box-btn-search")
    expect(searchBox).toContain('linear-gradient(135deg, var(--app-mineradio-accent')
  })

  it('aligns the settings page dark theme with the Mineradio accent system', () => {
    const settings = readComponent('src/setting/index.vue')

    // Settings menu selected uses Mineradio cyan accent (not blue)
    expect(settings).toContain("body[arco-theme='dark'] .xbyleftmenu .arco-menu-selected")
    expect(settings).toContain('rgba(0,245,212')
    expect(settings).toContain('var(--app-mineradio-accent')

    // Settings cards get glass treatment in dark theme
    expect(settings).toContain("body[arco-theme='dark'] .settingcard")
    expect(settings).toContain('backdrop-filter')

    // Settinghead accent line uses Mineradio accent
    expect(settings).toContain("body[arco-theme='dark'] .settinghead::after")
  })
})
