base: core22
name: shadowsocks-libev
version: '3.3.6'
summary: libev port of shadowsocks
description: |
  Shadowsocks-libev is a lightweight and secure SOCKS5 proxy for embedded
  devices and low-end boxes.

  It is rewritten in pure C and depends on libev, designed to be a
  lightweight implementation of the shadowsocks protocol.
grade: stable
confinement: strict

apps:
  ss-local:
    command: usr/bin/ss-local
    plugs: [network, network-bind]

  ss-local-daemon:
    command: usr/bin/ss-local
    daemon: simple
    plugs: [network, network-bind]

  ss-server:
    command: usr/bin/ss-server
    plugs: [network, network-bind]

  ss-server-daemon:
    command: usr/bin/ss-server
    daemon: simple
    plugs: [network, network-bind]

  ss-redir:
    command: usr/bin/ss-redir
    plugs: [network, network-bind]

  ss-tunnel:
    command: usr/bin/ss-tunnel
    plugs: [network, network-bind]

  ss-manager:
    command: usr/bin/ss-manager
    plugs: [network]

layout:
  /etc/shadowsocks-libev:
    bind: $SNAP_COMMON/etc/shadowsocks-libev

parts:
  shadowsocks-libev:
    plugin: cmake
    source: .
    source-type: git
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DWITH_DOC_MAN=OFF
      - -DBUILD_TESTING=OFF
    build-packages:
      - libpcre2-dev
      - libev-dev
      - libc-ares-dev
      - libmbedtls-dev
      - libsodium-dev
    stage-packages:
      - libc-ares2
      - libev4
      - libmbedcrypto7
      - libmbedtls14
      - libmbedx509-1
      - libpcre2-8-0
      - libsodium23
    override-build: |
      craftctl default
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/doc
