name: Build and test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.23
    - uses: actions/checkout@v2
    - run: make -j all
    - run: make -j test
