[package]
name = "mihomo_api"
edition = "2024"

[features]
debug = []

[dependencies]
reqwest = { version = "0.12.15", features = ["json"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"

[dev-dependencies]
tokio = { version = "1.44.1", features = ["rt", "macros"] }
