version: 2

builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/nodepass
    goos:
      - darwin
      - freebsd
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{ .Tag }}

archives:
  - formats: [tar.gz]
release:
  prerelease: true
  mode: replace
