with-expecter: true
inpackage: true
dir: .
packages:
  github.com/apernet/hysteria/core/v2/server:
    interfaces:
      udpIO:
        config:
          mockname: mockUDPIO
      udpEventLogger:
        config:
          mockname: mockUDPEventLogger
      UDPConn:
        config:
          mockname: mockUDPConn
