#!/bin/sh

. ./get-sysroot.sh

case "$ARCH" in
  Linux)
    WITH_GOOS=linux
    if [ "$target_os" = "android" ]; then
      WITH_GOOS=android
    fi
    case "$target_cpu" in
      x64) WITH_GOARCH=amd64;;
      x86) WITH_GOARCH=386;;
      arm64) WITH_GOARCH=arm64;;
      arm) WITH_GOARCH=arm;;
      mipsel) WITH_GOARCH=mipsle;;
      mips64el) WITH_GOARCH=mips64le;;
    esac
    shared_lib_name='libcronet.so'
    static_lib_name='libcronet_static.a'
  ;;
  MINGW*|MSYS*)
    WITH_GOOS=windows
    case "$target_cpu" in
      x64) WITH_GOARCH=amd64;;
      x86) WITH_GOARCH=386;;
      arm64) WITH_GOARCH=arm64;;
    esac
    shared_lib_name='cronet.dll.lib'
    dll_name='cronet.dll'
    static_lib_name='cronet_static.lib'
  ;;
  Darwin)
    WITH_GOOS=darwin
    case "$target_cpu" in
      x64) WITH_GOARCH=amd64;;
      arm64) WITH_GOARCH=arm64;;
    esac
    shared_lib_name='libcronet.dylib'
    static_lib_name='libcronet_static.a'
  ;;
esac

set -ex

mkdir -p out/Release/cronet

getflag() {
  local ninjafile=./out/Release/obj/components/cronet/$1.ninja
  local flagname="$2"
  grep "\<$flagname = " $ninjafile | cut -d= -f2- | sed 's/\$:/:/g;s/\\%/%/g;s/\\\$\$/\$/g' | sed "s#=\.\./#=$PWD/out/Release/../#g"
}

if [ "$target_os" = "android" ]; then
  WITH_SYSROOT="third_party/android_ndk/toolchains/llvm/prebuilt/linux-x86_64/sysroot"
fi

if [ "$ARCH" = "Darwin" ]; then
  WITH_SYSROOT="out/Release/$(getflag cronet_example_external ldflags | grep -o '[-]isysroot [^ ]*' | sed 's/-isysroot //')"
fi

if [ "$WITH_GOOS" = "windows" ]; then
  sys_lib_flags=$(grep -A1 '^rule link$' ./out/Release/toolchain.ninja \
    | tail -n1 \
    | grep -o '/nologo .* /PDB' \
    | sed 's#^/nologo ##;
           s# /PDB$##;
           s#C:\\Program Files (x86)\\Microsoft Visual Studio#./c/ProgramFilesx86MicrosoftVisualStudio#g;
           s#C:\\Program Files (x86)\\Windows Kits#./c/ProgramFilesx86WindowsKits#g;
           s#\\#/#g;
           s#"##g')
  mkdir -p ./out/Release/cronet/c/
  rm -f ./out/Release/cronet/c/ProgramFilesx86MicrosoftVisualStudio
  rm -f ./out/Release/cronet/c/ProgramFilesx86WindowsKits
  MSYS=winsymlinks:nativestrict ln -s 'C:\Program Files (x86)\Microsoft Visual Studio' ./out/Release/cronet/c/ProgramFilesx86MicrosoftVisualStudio
  MSYS=winsymlinks:nativestrict ln -s 'C:\Program Files (x86)\Windows Kits' ./out/Release/cronet/c/ProgramFilesx86WindowsKits
fi

#cat ./out/Release/toolchain.ninja
#cat ./out/Release/obj/net/naive.ninja
cat ./out/Release/obj/components/cronet/cronet_example_external.ninja
cat ./out/Release/obj/components/cronet/cronet_example_external_static.ninja

cp -a out/Release/$shared_lib_name out/Release/cronet/
if [ "$WITH_GOOS" = "windows" ]; then
  cp -a out/Release/$dll_name out/Release/cronet/
fi
cp -a out/Release/obj/components/cronet/$static_lib_name out/Release/cronet/
cp -a components/cronet/native/sample/cronet_example.go out/Release/cronet/
cp -a components/cronet/native/generated/cronet.idl_c.h out/Release/cronet/
cp -a components/cronet/native/include/cronet_c.h out/Release/cronet/
cp -a components/cronet/native/include/cronet_export.h out/Release/cronet/
cp -a components/grpc_support/include/bidirectional_stream_c.h out/Release/cronet/
if [ "$WITH_SYSROOT" ]; then
  ln -sf "$PWD/$WITH_SYSROOT" out/Release/cronet/sysroot
fi
ln -sf "$PWD/third_party/llvm-build/Release+Asserts" out/Release/cronet/llvm

# Extracts this manually because the sysroot flag generated by Chromium is bundled with other irrelevant stuff.
if [ "$WITH_SYSROOT" ]; then
  if [ "$ARCH" = "Darwin" ]; then
    sysroot_flag="-isysroot ./sysroot"
  else
    sysroot_flag="--sysroot=./sysroot"
  fi
fi

getshortflags() {
  sed 's/-mllvm[ :][^ ]*//g;s/ -march= / /g' | grep -Eo ' (--target=|-m|-arch |-fmsc-version=|-fuse-ld=|-Wl,--dynamic-linker=)[^ ]*' | tr -d '\n'
}

cflags_short="$(getflag cronet_example_external cflags | getshortflags) $sysroot_flag"
ldflags_short="$(getflag cronet_example_external ldflags | getshortflags) $sysroot_flag"
shared_ldflags="$(getflag cronet_example_external ldflags | sed 's/-isysroot [^ ]*//g;s#/NATVIS:[^ ]*##g') $sysroot_flag"
static_ldflags="$(getflag cronet_example_external_static ldflags | sed 's/-isysroot [^ ]*//g;s#/NATVIS:[^ ]*##g') $sysroot_flag"
shared_solibs="$(getflag cronet_example_external solibs)"
static_solibs="$(getflag cronet_example_external_static solibs)"
shared_libs="$(getflag cronet_example_external libs)"
static_libs="$(getflag cronet_example_external_static libs)"
shared_frameworks="$(getflag cronet_example_external frameworks)"
static_frameworks="$(getflag cronet_example_external_static frameworks)"

escapelinkerflags() {
  for i in "$@"; do
    echo -n " -Xlinker $i"
  done
}

if [ "$WITH_GOOS" = "windows" ]; then
  # https://github.com/golang/go/issues/46502
  cflags_short="$cflags_short -Wno-dll-attribute-on-redeclaration"
  # Ninja uses clang-cl.exe, but we need clang.exe with lld-link.exe here.
  ldflags_short="-fuse-ld=lld $ldflags_short"
  # Using lld-link.exe through clang.exe
  #shared_ldflags="$ldflags_short $(escapelinkerflags $shared_ldflags)"
  shared_ldflags="$ldflags_short"
  #static_ldflags="$ldflags_short $(escapelinkerflags $static_ldflags)"
  sys_lib_flags="$(echo $sys_lib_flags | sed 's#/MACHINE:[^ ]*##g;s/-libpath:/-L/g')"
  #sys_lib_flags="$(escapelinkerflags $sys_lib_flags)"
  #sys_lib_flags=
  find "$(dirname "$(which clang)")"/../ || true
  touch out/Release/cronet/llvm/lib/clang/15.0.0/lib/windows/mingwex.lib
  touch out/Release/cronet/llvm/lib/clang/15.0.0/lib/windows/mingw32.lib
fi

if [ "$ARCH" = "Linux" ]; then
  # tool("link") from build/toolchain/gcc_toolchain.gni
  shared_ldflags="$shared_ldflags $shared_solibs $shared_libs"
  static_ldflags="$static_ldflags $static_solibs $static_libs"
elif [ "$WITH_GOOS" = "windows" ]; then
  # tool("link") from build/toolchain/win/toolchain.gni
  shared_libs="./$shared_lib_name $(echo $shared_libs | sed 's/\([a-z0-9_]*\)\.lib/-l\1/g' )"
  #static_libs="./$static_lib_name $(echo $static_libs | sed 's/\([a-z0-9_]*\)\.lib/-l\1/g' )"
  # -target x86_64-pc-windows-gnu 
  shared_ldflags="-v $sys_lib_flags $shared_libs $shared_solibs $shared_ldflags"
  static_ldflags="$sys_lib_flags $static_libs $static_solibs $static_ldflags"
elif [ "$WITH_GOOS" = "darwin" ]; then
  # tool("link") from build/toolchain/apple/toolchain.gni
  shared_ldflags="$shared_ldflags $shared_frameworks $shared_solibs $shared_libs"
  static_ldflags="./$static_lib_name $static_ldflags $static_frameworks $static_solibs $static_libs"
fi

if [ "$WITH_GOARCH" = "arm" ]; then
  # CGO requires -marm, which conflicts with -mthumb.
  cflags_short=$(echo "$cflags_short" | sed 's/ -mthumb / /g')
fi

buildmode_flag='-buildmode=pie'

if [ "$WITH_GOARCH" = "mipsle" -o "$WITH_GOARCH" = "mips64le" ]; then
  # CGO does not support PIE for linux/mipsle,mipe64le.
  buildmode_flag=
elif [ "$WITH_GOARCH" = "arm64" -a "$WITH_GOOS" = "windows" ]; then
  # CGO does not support PIE for windows/arm64.
  buildmode_flag=
elif [ "$WITH_GOARCH" = "386" ]; then
  # Segfaults if built with PIE.
  buildmode_flag=
fi

if [ ! "$buildmode_flag" ]; then
  # Requires explicit -nopie otherwise clang adds -pie to lld sometime.
  shared_ldflags="$(echo "$shared_ldflags" | sed 's/ -pie / /g') -nopie"
  static_ldflags="$(echo "$static_ldflags" | sed 's/ -pie / /g') -nopie"
fi

# -Wl,--strip-debug is required to avoid section type mismatch for .debug_info etc on MIPS.
if [ "$WITH_GOARCH" = "mipsle" -o "$WITH_GOARCH" = "mips64le" ]; then
  shared_ldflags="$shared_ldflags -Wl,--strip-debug"
  static_ldflags="$static_ldflags -Wl,--strip-debug"
fi

if [ "$ARCH" = "Linux" ]; then
  # Saves explicit LD_LIBRARY_PATH for running cronet_example test case
  shared_ldflags="$shared_ldflags -Wl,-rpath,\$ORIGIN"
fi

cat >out/Release/cronet/go_env.sh <<EOF
[ "$WITH_GOOS" -a "$WITH_GOARCH" ] && export GOOS="$WITH_GOOS"
[ "$WITH_GOARCH" -a "$WITH_GOARCH" ] && export GOARCH="$WITH_GOARCH"
[ "$mips_float_abi" = "soft" ] && export GOMIPS=softfloat
buildmode_flag=$buildmode_flag
export PATH="\$PWD/llvm/bin:\$PATH"
export CC=clang
export CGO_CFLAGS="$cflags_short"
export CGO_LDFLAGS="$ldflags_short"
export CGO_ENABLED=1
export CGO_LDFLAGS_ALLOW=.*
EOF

cat >out/Release/cronet/link_shared.go <<EOF
package main

// #cgo LDFLAGS: $shared_ldflags
import "C"
EOF

cat >out/Release/cronet/link_static.go <<EOF
package main

// #cgo LDFLAGS: $static_ldflags
import "C"
EOF
