#!/bin/sh

. ./get-sysroot.sh

case "$ARCH" in
  Linux)
    WITH_GOOS=linux
    if [ "$target_os" = 'android' ]; then
      WITH_GOOS=android
    fi
    case "$target_cpu" in
      x64) WITH_GOARCH=amd64;;
      x86) WITH_GOARCH=386;;
      arm64) WITH_GOARCH=arm64;;
      arm) WITH_GOARCH=arm;;
      mipsel) WITH_GOARCH=mipsle;;
      mips64el) WITH_GOARCH=mips64le;;
    esac
    shared_lib_name='libcronet.so'
    static_lib_name='libcronet_static.a'
  ;;
  Windows)
    WITH_GOOS=windows
    case "$target_cpu" in
      x64) WITH_GOARCH=amd64;;
      x86) WITH_GOARCH=386;;
      arm64) WITH_GOARCH=arm64;;
    esac
    shared_lib_name='cronet.dll.lib'
    dll_name='cronet.dll'
    static_lib_name='cronet_static.lib'
  ;;
  Darwin)
    WITH_GOOS=darwin
    case "$target_cpu" in
      x64) WITH_GOARCH=amd64;;
      arm64) WITH_GOARCH=arm64;;
    esac
    shared_lib_name='libcronet.dylib'
    static_lib_name='libcronet_static.a'
  ;;
esac

set -ex

mkdir -p out/Release/cronet

getflag() {
  local ninjafile=./out/Release/obj/components/cronet/$1.ninja
  local flagname="$2"
  grep "\<$flagname = " $ninjafile | cut -d= -f2- | sed 's/\$:/:/g;s/\\%/%/g;s/\\\$\$/\$/g' | sed "s#=\.\./#=$PWD/out/Release/../#g"
}

if [ "$target_os" = 'android' ]; then
  WITH_SYSROOT='third_party/android_ndk/toolchains/llvm/prebuilt/linux-x86_64/sysroot'
fi

if [ "$ARCH" = 'Darwin' ]; then
  # TODO: smarter way to get this path
  WITH_SYSROOT="out/Release/$(getflag cronet_example_external ldflags | grep -o '[-]isysroot [^ ]*' | sed 's/-isysroot //')"
fi

if [ "$ARCH" = 'Windows' ]; then
  alias ln='MSYS=winsymlinks:nativestrict ln'
  # sys_lib_flags=$(grep -A1 '^rule link$' ./out/Release/toolchain.ninja \
  #   | tail -n1 \
  #   | grep -o '/nologo .* /PDB' \
  #   | sed 's#^/nologo ##;
  #          s# /PDB$##;
  #          s#C:\\Program Files (x86)\\Microsoft Visual Studio#./c/ProgramFilesx86MicrosoftVisualStudio#g;
  #          s#C:\\Program Files (x86)\\Windows Kits#./c/ProgramFilesx86WindowsKits#g;
  #          s#-libpath:......third_party.llvm-build.Release.Asserts[^ ]*##g;
  #          s#\\#/#g;
  #          s#"##g')
  #mkdir -p ./out/Release/cronet/c/
  #rm -f ./out/Release/cronet/c/ProgramFilesx86MicrosoftVisualStudio
  #rm -f ./out/Release/cronet/c/ProgramFilesx86WindowsKits
  #MSYS=winsymlinks:nativestrict ln -s 'C:\Program Files (x86)\Microsoft Visual Studio' ./out/Release/cronet/c/ProgramFilesx86MicrosoftVisualStudio
  #MSYS=winsymlinks:nativestrict ln -s 'C:\Program Files (x86)\Windows Kits' ./out/Release/cronet/c/ProgramFilesx86WindowsKits
  sys_lib_flags=$(grep -A1 '^rule link$' ./out/Release/toolchain.ninja | tail -n1 | grep -o '/MACHINE:[^ ]*')
fi

#cat ./out/Release/toolchain.ninja
#cat ./out/Release/obj/net/naive.ninja
grep /DEFAULTLIB ./out/Release/toolchain.ninja || true
grep /DEFAULTLIB ./out/Release/obj/net/naive.ninja || true
cat ./out/Release/obj/components/cronet/cronet_example_external.ninja
cat ./out/Release/obj/components/cronet/cronet_example_external_static.ninja

cp -a out/Release/$shared_lib_name out/Release/cronet/
if [ "$ARCH" = 'Windows' ]; then
  cp -a out/Release/$dll_name out/Release/cronet/
fi
cp -a out/Release/obj/components/cronet/$static_lib_name out/Release/cronet/
cp -a components/cronet/native/sample/cronet_example.go out/Release/cronet/
cp -a components/cronet/native/generated/cronet.idl_c.h out/Release/cronet/
cp -a components/cronet/native/include/cronet_c.h out/Release/cronet/
cp -a components/cronet/native/include/cronet_export.h out/Release/cronet/
cp -a components/grpc_support/include/bidirectional_stream_c.h out/Release/cronet/
if [ "$WITH_SYSROOT" ]; then
  ln -sfn "$PWD/$WITH_SYSROOT" out/Release/cronet/sysroot
fi
ln -sfn "$PWD/third_party/llvm-build/Release+Asserts" out/Release/cronet/llvm

# Extracts this manually because the sysroot flag generated by Chromium is bundled with other irrelevant stuff.
if [ "$WITH_SYSROOT" ]; then
  if [ "$ARCH" = 'Darwin' ]; then
    sysroot_flag='-isysroot ./sysroot'
  else
    sysroot_flag='--sysroot=./sysroot'
  fi
fi

getshortflags() {
  # -mllvm: avoid confusion with -m*; we don't use this flag in short flags anyway.
  # ' -march= ': artifact during OpenWrt build
  # -arch xyz: Mac specific
  # -fmsc-version=: Windows specific
  # -Wl,--dynamic-linker=: OpenWrt specific
  sed 's/-mllvm[ :][^ ]*//g;s/ -march= / /g' | grep -Eo ' (-fuse-ld=|--target=|-m|-arch |-fmsc-version=|-Wl,--dynamic-linker=)[^ ]*' | tr -d '\n'
}

cflags_short="$(getflag cronet_example_external cflags | getshortflags) $sysroot_flag"
ldflags_short="$(getflag cronet_example_external ldflags | getshortflags) $sysroot_flag"
# -isysroot: TODO: can this be extracted without parsing ninja file?
# NATVIS: Cannot be turned off cleanly with GN flags, so removes it manually here.
shared_ldflags="$(getflag cronet_example_external ldflags | sed 's/-isysroot [^ ]*//g;s#/NATVIS:[^ ]*##g') $sysroot_flag"
static_ldflags="$(getflag cronet_example_external_static ldflags | sed 's/-isysroot [^ ]*//g;s#/NATVIS:[^ ]*##g') $sysroot_flag"
shared_solibs="$(getflag cronet_example_external solibs)"
static_solibs="$(getflag cronet_example_external_static solibs)"
shared_libs="$(getflag cronet_example_external libs)"
static_libs="$(getflag cronet_example_external_static libs)"
shared_frameworks="$(getflag cronet_example_external frameworks)"
static_frameworks="$(getflag cronet_example_external_static frameworks)"

escapelinkerflags() {
  for i in "$@"; do
    if echo "$i" | grep -q ','; then
      echo -n " -Xlinker $i"
    else
      echo -n " -Wl,$i"
    fi
  done
}

if [ "$ARCH" = 'Windows' ]; then
  # -Wno-dll-attribute-on-redeclaration: https://github.com/golang/go/issues/46502
  cflags_short="$cflags_short -v -Wno-dll-attribute-on-redeclaration"
  # Chromium uses clang-cl.exe, but CGO officially only supports GCC/MinGW on Windows. See https://github.com/golang/go/issues/17014.
  # 1. CGO hardcodes GCC flags incompatible with clang-cl.exe, so an extra clang.exe is required (Chromium only provides clang-cl.exe).
  # 2. We need CGO to link LLVM bitcode from Chromium, so ld cannot work and lld is required.
  # 3. CGO passes GCC options not understood by lld, so an extra lld wrapper is required to remove those options.
  # 4. I didn't figure out a way to make the whole pipeline use lld-link-wrapper directly:
  #   * `-fuse-ld=lld --ld-path=lld-link-wrapper` reports `--ld-path` is an unknown argument.
  #   * `-fuse-ld=.../lld-link-wrapper.exe` creates garbled linker path.
  #   So uses a hack to rename lld-link.exe to lld-link-old.exe which is called from the wrapper "lld-link.exe".
  # 5. lld 13 does not work with bitcode produced by Chromium's lld 15.
  #    So copies clang 13 from environment to Chromium's LLVM bin directory, and uses clang 13 together with lld 15.
  ldflags_short="-fuse-ld=lld $ldflags_short -v"
  if [ "$WITH_GOARCH" = '386' ]; then
    # Chromium enables /SAFESEH for x86 with clang-cl, but CGO compiles gcc_386.S with GCC which does not support /SAFESEH.
    # So has to remove /SAFESEH for x86.
    shared_ldflags="$shared_ldflags /SAFESEH:NO"
    static_ldflags="$static_ldflags /SAFESEH:NO"
    ldflags_short="$ldflags_short -Wl,/SAFESEH:NO"
  fi
  if [ "$WITH_GOARCH" = 'arm64' ]; then
    ldflags_short="$ldflags_short"
  fi
  sys_lib_flags="$(escapelinkerflags $sys_lib_flags)"
  ldflags_short="$ldflags_short $sys_lib_flags"
  # Using lld-link.exe through clang.exe
  shared_ldflags="$ldflags_short $(escapelinkerflags $shared_ldflags)"
  #shared_ldflags="$ldflags_short"
  static_ldflags="$ldflags_short $(escapelinkerflags $static_ldflags)"

  cat >lld-link.cc <<EOF
#include <cstdio>
#include <cstdlib>
#include <string>
#include <cstring>

int main(int argc, char** argv) {
  std::string cmd = "lld-link-old";
  for (int i = 1; i < argc; ++i) {
    fprintf(stderr, "argv[%d]: %s\n", i, argv[i]);
    if (strcmp(argv[i], "--tsaware") == 0) continue;
    if (strcmp(argv[i], "--nxcompat") == 0) continue;
    if (strstr(argv[i], "--major-os-version=") == argv[i]) continue;
    if (strstr(argv[i], "--minor-os-version=") == argv[i]) continue;
    if (strstr(argv[i], "--major-subsystem-version=") == argv[i]) continue;
    if (strstr(argv[i], "--minor-subsystem-version=") == argv[i]) continue;
    if (strcmp(argv[i], "--dynamicbase") == 0) continue;
    if (strcmp(argv[i], "--high-entropy-va") == 0) continue;
    if (strcmp(argv[i], "-T") == 0) {
      ++i;
      continue;
    }
    if (strcmp(argv[i], "--start-group") == 0) continue;
    if (strcmp(argv[i], "mingwex.lib") == 0) continue;
    if (strcmp(argv[i], "mingw32.lib") == 0) continue;
    if (strcmp(argv[i], "--end-group") == 0) continue;
    if (strchr(argv[i], ' ') != nullptr) {
      cmd.append(" \"").append(argv[i]).append("\"");
    } else {
      cmd.append(" ").append(argv[i]);
    }
  }
  fprintf(stderr, "cmd: %s\n", cmd.c_str());
  return system(cmd.c_str());
}
EOF
  cp 'C:\Program Files\LLVM\bin\clang.exe' ./third_party/llvm-build/Release+Asserts/bin/
  # TODO: smarter way to get this path
  ln -sfn 'C:\Program Files\LLVM\lib\clang\13.0.1' ./third_party/llvm-build/Release+Asserts/lib/clang/
  mv ./third_party/llvm-build/Release+Asserts/bin/lld-link.exe ./third_party/llvm-build/Release+Asserts/bin/lld-link-old.exe
  clang lld-link.cc -o ./third_party/llvm-build/Release+Asserts/bin/lld-link.exe
fi

if [ "$ARCH" = 'Linux' ]; then
  # tool("link") from build/toolchain/gcc_toolchain.gni
  shared_ldflags="$shared_ldflags $shared_solibs $shared_libs"
  static_ldflags="$static_ldflags $static_solibs $static_libs"
elif [ "$ARCH" = 'Windows' ]; then
  # tool("link") from build/toolchain/win/toolchain.gni
  # TODO: can xyz.lib work without -Wl,?
  shared_libs="./$shared_lib_name $(echo $shared_libs | sed 's/[a-z0-9_]*\.lib/-Wl,&/g' )"
  static_libs="./$static_lib_name $(echo $static_libs | sed 's/[a-z0-9_]*\.lib/-Wl,&/g' )"
  shared_ldflags="-v $sys_lib_flags $shared_libs $shared_solibs $shared_ldflags"
  static_ldflags="-v $sys_lib_flags $static_libs $static_solibs $static_ldflags"
elif [ "$ARCH" = 'Darwin' ]; then
  # tool("link") from build/toolchain/apple/toolchain.gni
  shared_ldflags="$shared_ldflags $shared_frameworks $shared_solibs $shared_libs"
  static_ldflags="./$static_lib_name $static_ldflags $static_frameworks $static_solibs $static_libs"
fi

if [ "$WITH_GOARCH" = 'arm' ]; then
  # CGO requires -marm, which conflicts with -mthumb.
  cflags_short=$(echo "$cflags_short" | sed 's/ -mthumb / /g')
fi

buildmode_flag='-buildmode=pie'

if [ "$WITH_GOARCH" = 'mipsle' -o "$WITH_GOARCH" = 'mips64le' ]; then
  # CGO does not support PIE for linux/mipsle,mipe64le.
  buildmode_flag=
elif [ "$WITH_GOARCH" = 'arm64' -a "$ARCH" = 'Windows' ]; then
  # CGO does not support PIE for windows/arm64.
  buildmode_flag=
elif [ "$WITH_GOARCH" = '386' ]; then
  # Segfaults if built with PIE.
  buildmode_flag=
fi

if [ ! "$buildmode_flag" ]; then
  # Requires explicit -nopie otherwise clang adds -pie to lld sometime.
  shared_ldflags="$(echo "$shared_ldflags" | sed 's/ -pie / /g') -nopie"
  static_ldflags="$(echo "$static_ldflags" | sed 's/ -pie / /g') -nopie"
fi

# -Wl,--strip-debug is required to avoid section type mismatch for .debug_info etc on MIPS.
if [ "$WITH_GOARCH" = 'mipsle' -o "$WITH_GOARCH" = 'mips64le' ]; then
  shared_ldflags="$shared_ldflags -Wl,--strip-debug"
  static_ldflags="$static_ldflags -Wl,--strip-debug"
fi

if [ "$ARCH" = 'Linux' ]; then
  # Saves explicit LD_LIBRARY_PATH for running cronet_example test case
  shared_ldflags="$shared_ldflags -Wl,-rpath,\$ORIGIN"
fi

cat >out/Release/cronet/go_env.sh <<EOF
[ "$WITH_GOOS" -a "$WITH_GOARCH" ] && export GOOS="$WITH_GOOS"
[ "$WITH_GOARCH" -a "$WITH_GOARCH" ] && export GOARCH="$WITH_GOARCH"
[ "$mips_float_abi" = "soft" ] && export GOMIPS=softfloat
buildmode_flag=$buildmode_flag
export PATH="\$PWD/llvm/bin:\$PATH"
export CC=clang
export CGO_CFLAGS="$cflags_short"
export CGO_LDFLAGS="$ldflags_short"
export CGO_ENABLED=1
export CGO_LDFLAGS_ALLOW=.*
EOF

cat >out/Release/cronet/link_shared.go <<EOF
package main

// #cgo LDFLAGS: $shared_ldflags
import "C"
EOF

cat >out/Release/cronet/link_static.go <<EOF
package main

// #cgo LDFLAGS: $static_ldflags
import "C"
EOF
