#!/bin/sh

. ./get-sysroot.sh

case "$ARCH" in
  Linux)
    WITH_GOOS=linux
    if [ "$target_os" = "android" ]; then
      WITH_GOOS=android
    fi
    case "$target_cpu" in
      x64) WITH_GOARCH=amd64;;
      x86) WITH_GOARCH=386;;
      arm64) WITH_GOARCH=arm64;;
      arm) WITH_GOARCH=arm;;
      mipsel) WITH_GOARCH=mipsle;;
      mips64el) WITH_GOARCH=mips64le;;
    esac
    shared_lib_name='libcronet.so'
    static_lib_name='libcronet_static.a'
  ;;
  MINGW*|MSYS*)
    WITH_GOOS=windows
    case "$target_cpu" in
      x64) WITH_GOARCH=amd64;;
      x86) WITH_GOARCH=386;;
      arm64) WITH_GOARCH=arm64;;
    esac
    shared_lib_name='cronet.dll'
    static_lib_name='cronet_static.lib'
  ;;
  Darwin)
    WITH_GOOS=darwin
    case "$target_cpu" in
      x64) WITH_GOARCH=amd64;;
      arm64) WITH_GOARCH=arm64;;
    esac
    shared_lib_name='libcronet.dylib'
    static_lib_name='libcronet_static.a'
  ;;
esac

set -ex

getflag() {
  local ninjafile=./out/Release/obj/components/cronet/cronet_example_external.ninja
  local flagname="$1"
  grep "\<$flagname = " $ninjafile | cut -d= -f2- | sed 's/\$:/:/g;s/\\%/%/g;s/\\\$\$/\$/g' | sed "s#=\.\./#=$PWD/out/Release/../#g"
}

if [ "$target_os" = "android" ]; then
  WITH_SYSROOT="third_party/android_ndk/toolchains/llvm/prebuilt/linux-x86_64/sysroot"
fi

if [ "$ARCH" = "Darwin" ]; then
  sysroot="out/Release/$(getflag ldflags | grep -o '[-]isysroot [^ ]*' | sed 's/-isysroot //')"
  WITH_SYSROOT="$sysroot"
fi

cat ./out/Release/toolchain.ninja
cat ./out/Release/obj/net/naive.ninja
cat ./out/Release/obj/components/cronet/cronet_example_external.ninja
cat ./out/Release/obj/components/cronet/cronet_example_external_static.ninja

if [ "$WITH_GOOS" = "windows" ]; then
  sys_lib_flags=$(grep -A1 '^rule link$' ./out/Release/toolchain.ninja | tail -n1 | grep -o '/nologo .* /PDB' | sed 's#^/nologo ##;s# /PDB$##')
fi

# Mac link: {{ldflags}} {{frameworks}} {{solibs}} {{libs}} 
# Windows link: ${sys_lib_flags} {{libs}} {{solibs}} {{ldflags}}
mkdir -p out/Release/cronet
cp -a out/Release/$shared_lib_name out/Release/cronet/
if [ "$WITH_GOOS" = "windows" ]; then
  cp -a out/Release/$shared_lib_name.lib out/Release/cronet/
fi
cp -a out/Release/obj/components/cronet/$static_lib_name out/Release/cronet/
cp -a components/cronet/native/sample/cronet_example.go out/Release/cronet/
cp -a components/cronet/native/generated/cronet.idl_c.h out/Release/cronet/
cp -a components/cronet/native/include/cronet_c.h out/Release/cronet/
cp -a components/cronet/native/include/cronet_export.h out/Release/cronet/
cp -a components/grpc_support/include/bidirectional_stream_c.h out/Release/cronet/
if [ "$WITH_SYSROOT" ]; then
  ln -sf "$PWD/$WITH_SYSROOT" out/Release/cronet/sysroot
  ls -l out/Release/cronet/sysroot
  ls -l out/Release/cronet/sysroot/
fi
ln -sf "$PWD/third_party/llvm-build/Release+Asserts/bin" out/Release/cronet/llvm
ls -l out/Release/cronet/llvm/

# Extracts this manually because the sysroot flag generated by Chromium is bundled with other irrelevant stuff.
if [ "$WITH_SYSROOT" ]; then
  if [ "$ARCH" = "Darwin" ]; then
    sysroot_flag="-isysroot ./sysroot"
  else
    sysroot_flag="--sysroot=./sysroot"
  fi
fi

cflags_short="$(getflag cflags | sed 's/-mllvm[ :][^ ]*//g;s/ -march= / /g' | grep -Eo ' (--target=[^ ]*|-m[^ ]*|-arch [^ ]*|-fmsc-version=[^ ]*)' | tr -d '\n') $sysroot_flag"
ldflags_short="$(getflag ldflags | grep -Eo ' (--target=[^ ]*|-fuse-ld=lld|-Wl,--dynamic-linker=[^ ]*|-m32|-arch [^ ]*)' | tr -d '\n') $sysroot_flag"
ldflags="$(getflag ldflags | sed 's/-isysroot [^ ]*'//g) $sysroot_flag"

#if [ "$ARCH" = "Darwin" ]; then
#  #ldflags_short="$ldflags_short -L$PWD/$sysroot/usr/lib"
#  #ldflags="$ldflags -L$sysroot/usr/lib"
#fi

if [ "$WITH_GOOS" = "windows" ]; then
  # https://github.com/golang/go/issues/46502
  cflags_short="$cflags_short -Wno-dll-attribute-on-redeclaration"
  ldflags_short="-fuse-ld=lld $ldflags_short"
  # Using clang.exe instead of clang-cl.exe here
  ldflags="$ldflags_short -Wl,--color-diagnostics -Wl,-mllvm:-instcombine-lower-dbg-declare=0 -Wl,/opt:lldltojobs=all -Wl,-mllvm:-import-instr-limit=5 -Wl,/lldltocache:thinlto-cache -Wl,/lldltocachepolicy:cache_size=10%:cache_size_bytes=40g:cache_size_files=100000 -Wl,/lldignoreenv -Wl,/OPT:REF -Wl,/OPT:ICF -Wl,/INCREMENTAL:NO -Wl,/FIXED:NO -Wl,/OPT:NOLLDTAILMERGE -Wl,/PROFILE -Wl,/PDBSourcePath:o:\fake\prefix -Wl,/opt:lldlto=2 -Wl,/DEFAULTLIB:libcpmt.lib -Wl,/FIXED:NO -Wl,/ignore:4199 -Wl,/ignore:4221 -Wl,/NXCOMPAT -Wl,/DYNAMICBASE -Wl,/INCREMENTAL:NO -Wl,/SUBSYSTEM:CONSOLE -Wl,/guard:cf -Wl,/DELAYLOAD:cfgmgr32.dll -Wl,/DELAYLOAD:powrprof.dll -Wl,/DELAYLOAD:setupapi.dll -pie"
fi

if [ "$WITH_GOARCH" = "arm" ]; then
  # CGO requires -marm, which conflicts with -mthumb.
  cflags_short=$(echo "$cflags_short" | sed 's/ -mthumb / /g')
fi

buildmode_flag='-buildmode=pie'

# CGO does not support PIE for linux/mipsle,mipe64le.
if [ "$WITH_GOARCH" = "mipsle" -o "$WITH_GOARCH" = "mips64le" ]; then
  # -Wl,--strip-debug is required to avoid section type mismatch for .debug_info etc.
  ldflags="$(echo "$ldflags" | sed 's/ -pie / /g') -nopie"
  buildmode_flag=
fi

# -Wl,--strip-debug is required to avoid section type mismatch for .debug_info etc.
if [ "$WITH_GOARCH" = "mipsle" -o "$WITH_GOARCH" = "mips64le" ]; then
  ldflags="$ldflags -Wl,--strip-debug"
  buildmode_flag=
fi

# Segfaults if built with PIE.
if [ "$WITH_GOARCH" = "386" ]; then
  ldflags="$(echo "$ldflags" | sed 's/ -pie / /g') -nopie"
  buildmode_flag=
fi

# CGO does not support PIE for windows/arm64.
if [ "$WITH_GOARCH" = "arm64" -a "$WITH_GOOS" = "windows" ]; then
  ldflags="$(echo "$ldflags" | sed 's/ -pie / /g') -nopie"
  buildmode_flag=
fi

if [ "$WITH_GOOS" = "windows" ]; then
  cc=clang
  shared_lib_name="$shared_lib_name.lib"
  shared_libs='advapi32.lib comdlg32.lib dbghelp.lib dnsapi.lib gdi32.lib msimg32.lib odbc32.lib odbccp32.lib oleaut32.lib shell32.lib shlwapi.lib user32.lib usp10.lib uuid.lib version.lib wininet.lib winmm.lib winspool.lib ws2_32.lib delayimp.lib kernel32.lib ole32.lib'
else
  cc=clang
  ldflags="$ldflags -Wl,-rpath,\$ORIGIN"
  static_libs='-lm -lpthread -latomic'
fi

cat >out/Release/cronet/go_env.sh <<EOF
[ "$WITH_GOOS" -a "$WITH_GOARCH" ] && export GOOS="$WITH_GOOS"
[ "$WITH_GOARCH" -a "$WITH_GOARCH" ] && export GOARCH="$WITH_GOARCH"
[ "$mips_float_abi" = "soft" ] && export GOMIPS=softfloat
buildmode_flag=$buildmode_flag
export PATH="\$PWD/llvm:\$PATH"
export CC=$cc
export CGO_CFLAGS="$cflags_short"
export CGO_LDFLAGS="$ldflags_short"
export CGO_ENABLED=1
export CGO_LDFLAGS_ALLOW=.*
EOF

cat >out/Release/cronet/link_shared.go <<EOF
package main

// #cgo LDFLAGS: $ldflags ./$shared_lib_name $shared_libs
import "C"
EOF

cat >out/Release/cronet/link_static.go <<EOF
package main

// #cgo LDFLAGS: $ldflags ./$static_lib_name $static_libs
import "C"
EOF
