export type KoodoParityStatus = 'missing' | 'partial' | 'complete' | 'excluded'

export interface KoodoParityFeature {
  id: string
  label: string
  area: 'manager' | 'reader' | 'shared' | 'excluded'
  status: KoodoParityStatus
  koodoSource: string[]
  targetFiles: string[]
  reason?: string
}

export const KOODO_PARITY_FEATURES: KoodoParityFeature[] = [
  {
    id: 'account-login',
    label: 'Account login',
    area: 'excluded',
    status: 'excluded',
    reason: 'Excluded by user: account features are out of scope',
    koodoSource: ['koodo-reader/src/pages/login/component.tsx'],
    targetFiles: [],
  },
  {
    id: 'cloud-sync',
    label: 'Cloud sync',
    area: 'excluded',
    status: 'excluded',
    reason: 'Excluded by user: sync features are out of scope',
    koodoSource: ['koodo-reader/src/utils/storage/syncService.ts'],
    targetFiles: [],
  },
  {
    id: 'remote-backup-sync',
    label: 'Remote backup sync',
    area: 'excluded',
    status: 'excluded',
    reason: 'Excluded by user: sync features are out of scope',
    koodoSource: ['koodo-reader/src/components/dialogs/backupDialog'],
    targetFiles: [],
  },
  {
    id: 'manager-shell-visuals',
    label: 'Manager shell, sidebar, header, footer',
    area: 'manager',
    status: 'partial',
    koodoSource: [
      'koodo-reader/src/pages/manager/component.tsx',
      'koodo-reader/src/containers/sidebar',
      'koodo-reader/src/containers/header',
      'koodo-reader/src/components/footer',
    ],
    targetFiles: ['src/layout/PageBookLibrary.vue', 'src/layout/book-manager/BookManagerShell.vue'],
  },
  {
    id: 'manager-header-buttons',
    label: 'Header import/sort/view/settings/buttons',
    area: 'manager',
    status: 'partial',
    koodoSource: [
      'koodo-reader/src/containers/header/component.tsx',
      'koodo-reader/src/components/dialogs/sortBookDialog/component.tsx',
    ],
    targetFiles: ['src/layout/book-manager/BookManagerHeader.vue', 'src/utils/bookManagerActions.ts'],
  },
  {
    id: 'manager-sidebar-tabs',
    label: 'Side menu and counts',
    area: 'manager',
    status: 'partial',
    koodoSource: ['koodo-reader/src/containers/sidebar/component.tsx', 'koodo-reader/src/constants/sideMenu.tsx'],
    targetFiles: ['src/layout/book-manager/BookManagerSidebar.vue', 'src/utils/bookManagerParity.ts'],
  },
  {
    id: 'manager-book-card',
    label: 'Book card item visual/actions',
    area: 'manager',
    status: 'partial',
    koodoSource: ['koodo-reader/src/components/bookCardItem/component.tsx'],
    targetFiles: ['src/layout/BookCardItem.vue'],
  },
  {
    id: 'manager-book-cover',
    label: 'Book cover item visual/actions',
    area: 'manager',
    status: 'partial',
    koodoSource: ['koodo-reader/src/components/bookCoverItem/component.tsx'],
    targetFiles: ['src/layout/BookCoverItem.vue'],
  },
  {
    id: 'manager-book-list',
    label: 'Book list item visual/actions',
    area: 'manager',
    status: 'partial',
    koodoSource: ['koodo-reader/src/components/bookListItem/component.tsx'],
    targetFiles: ['src/layout/BookListItem.vue'],
  },
  {
    id: 'manager-view-mode',
    label: 'View mode switcher',
    area: 'manager',
    status: 'partial',
    koodoSource: ['koodo-reader/src/components/viewMode/component.tsx'],
    targetFiles: ['src/layout/book-manager/BookManagerHeader.vue', 'src/store/booklibrary.ts'],
  },
  {
    id: 'manager-sort-dialog',
    label: 'Book and note sort menus',
    area: 'manager',
    status: 'partial',
    koodoSource: ['koodo-reader/src/components/dialogs/sortBookDialog/component.tsx'],
    targetFiles: ['src/utils/bookManagerParity.ts', 'src/layout/book-manager/BookManagerHeader.vue'],
  },
  {
    id: 'manager-local-import',
    label: 'Local file import and drag/drop',
    area: 'manager',
    status: 'partial',
    koodoSource: [
      'koodo-reader/src/components/importLocal/component.tsx',
      'koodo-reader/src/pages/manager/component.tsx',
    ],
    targetFiles: ['src/layout/PageBookLibrary.vue', 'src/utils/bookManagerActions.ts'],
  },
  {
    id: 'manager-opds-import',
    label: 'OPDS import dialog',
    area: 'manager',
    status: 'partial',
    koodoSource: ['koodo-reader/src/components/dialogs/opdsDialog'],
    targetFiles: ['src/layout/book-manager/BookManagerHeader.vue', 'src/layout/PageBookLibrary.vue', 'src/utils/bookOpds.ts'],
  },
  {
    id: 'manager-add-edit-delete-dialogs',
    label: 'Add/edit/delete dialogs',
    area: 'manager',
    status: 'partial',
    koodoSource: [
      'koodo-reader/src/components/dialogs/addDialog',
      'koodo-reader/src/components/dialogs/editDialog',
      'koodo-reader/src/components/dialogs/deleteDialog',
    ],
    targetFiles: ['src/layout/PageBookLibrary.vue', 'src/store/booklibrary.ts'],
  },
  {
    id: 'manager-shelves',
    label: 'Shelves, shelf sort, startup shelf',
    area: 'manager',
    status: 'partial',
    koodoSource: ['koodo-reader/src/components/selectBook', 'koodo-reader/src/components/dialogs/sortShelfDialog'],
    targetFiles: ['src/store/booklibrary.ts', 'src/utils/bookManagerParity.ts'],
  },
  {
    id: 'manager-favorites-trash',
    label: 'Favorites and deleted books',
    area: 'manager',
    status: 'complete',
    koodoSource: ['koodo-reader/src/containers/lists/deletedBookList'],
    targetFiles: ['src/store/booklibrary.ts', 'src/layout/PageBookLibrary.vue'],
  },
  {
    id: 'manager-notes-highlights',
    label: 'Global notes/highlights lists',
    area: 'manager',
    status: 'complete',
    koodoSource: ['koodo-reader/src/containers/lists/noteList', 'koodo-reader/src/containers/lists/cardList'],
    targetFiles: ['src/layout/PageBookLibrary.vue', 'src/utils/bookManagerParity.ts'],
  },
  {
    id: 'manager-note-tags',
    label: 'Global note tag CRUD',
    area: 'manager',
    status: 'partial',
    koodoSource: ['koodo-reader/src/components/noteTag/component.tsx'],
    targetFiles: ['src/store/booklibrary.ts', 'src/layout/PageBookLibrary.vue'],
  },
  {
    id: 'manager-stats',
    label: 'Stats page',
    area: 'manager',
    status: 'partial',
    koodoSource: ['koodo-reader/src/pages/stats/component.tsx'],
    targetFiles: ['src/layout/StatsPage.vue', 'src/store/booklibrary.ts'],
  },
  {
    id: 'manager-protection',
    label: 'Protection overlay',
    area: 'manager',
    status: 'partial',
    koodoSource: ['koodo-reader/src/components/protection/component.tsx', 'koodo-reader/src/utils/protectionUtil.ts'],
    targetFiles: ['src/layout/book-manager/BookManagerShell.vue', 'src/utils/bookManagerActions.ts'],
  },
  {
    id: 'reader-shell',
    label: 'Reader shell visual frame',
    area: 'reader',
    status: 'partial',
    koodoSource: ['koodo-reader/src/pages/reader/component.tsx', 'koodo-reader/src/pages/reader/index.css'],
    targetFiles: ['src/layout/BookReaderModal.vue', 'src/layout/book-reader/ReaderShell.vue'],
  },
  {
    id: 'reader-panel-buttons',
    label: 'Reader panel buttons and arrows',
    area: 'reader',
    status: 'partial',
    koodoSource: ['koodo-reader/src/containers/panels', 'koodo-reader/src/components/arrow'],
    targetFiles: ['src/layout/book-reader/ReaderShell.vue', 'src/layout/book-reader/ReaderPanelButton.vue'],
  },
  {
    id: 'reader-navigation-panel',
    label: 'Navigation/TOC panel',
    area: 'reader',
    status: 'partial',
    koodoSource: ['koodo-reader/src/containers/panels/navigationPanel'],
    targetFiles: ['src/layout/BookReaderModal.vue', 'src/layout/book-reader/ReaderShell.vue'],
  },
  {
    id: 'reader-operation-panel',
    label: 'Operation/top panel',
    area: 'reader',
    status: 'partial',
    koodoSource: ['koodo-reader/src/containers/panels/operationPanel'],
    targetFiles: ['src/layout/book-reader/ReaderShell.vue'],
  },
  {
    id: 'reader-progress-panel',
    label: 'Bottom progress panel',
    area: 'reader',
    status: 'partial',
    koodoSource: ['koodo-reader/src/containers/panels/progressPanel'],
    targetFiles: ['src/layout/BookReaderModal.vue', 'src/utils/bookReaderState.ts'],
  },
  {
    id: 'reader-settings-complete',
    label: 'Complete reader settings',
    area: 'reader',
    status: 'partial',
    koodoSource: [
      'koodo-reader/src/containers/panels/settingPanel',
      'koodo-reader/src/constants/settingList.tsx',
    ],
    targetFiles: ['src/layout/book-reader/ReaderSettingsPanel.vue', 'src/utils/bookReaderPreferences.ts'],
  },
  {
    id: 'reader-selection-popup',
    label: 'Selected text PopupBox',
    area: 'reader',
    status: 'partial',
    koodoSource: ['koodo-reader/src/components/popups/popupBox', 'koodo-reader/src/constants/popupList.tsx'],
    targetFiles: ['src/layout/book-reader/ReaderSelectionPopup.vue', 'src/utils/bookPopupActions.ts'],
  },
  {
    id: 'reader-popup-note',
    label: 'PopupNote edit/delete/tags/color',
    area: 'reader',
    status: 'partial',
    koodoSource: ['koodo-reader/src/components/popups/popupNote'],
    targetFiles: ['src/layout/BookReaderModal.vue', 'src/store/booklibrary.ts'],
  },
  {
    id: 'reader-image-viewer',
    label: 'Image viewer',
    area: 'reader',
    status: 'complete',
    koodoSource: ['koodo-reader/src/components/imageViewer/component.tsx'],
    targetFiles: ['src/utils/bookImageViewer.ts', 'src/layout/BookReaderModal.vue'],
  },
  {
    id: 'reader-reference-popup',
    label: 'Footnote/reference popup',
    area: 'reader',
    status: 'partial',
    koodoSource: ['koodo-reader/src/components/popups/popupRefer'],
    targetFiles: ['src/layout/book-reader/ReaderReferencePopup.vue', 'src/utils/bookRefer.ts'],
  },
  {
    id: 'reader-search',
    label: 'Book search',
    area: 'reader',
    status: 'complete',
    koodoSource: ['koodo-reader/src/containers/panels/searchPanel'],
    targetFiles: ['src/utils/bookReader.ts', 'src/layout/BookReaderModal.vue'],
  },
  {
    id: 'reader-tts',
    label: 'Text to speech',
    area: 'reader',
    status: 'partial',
    koodoSource: ['koodo-reader/src/components/textToSpeech', 'koodo-reader/src/utils/reader/ttsUtil.ts'],
    targetFiles: ['src/utils/bookTextToSpeech.ts', 'src/layout/BookReaderModal.vue'],
  },
  {
    id: 'reader-ai-preserve-migrate',
    label: 'Preserve existing AI/RAG/chat and migrate to Koodo-style controls',
    area: 'reader',
    status: 'partial',
    koodoSource: [
      'koodo-reader/src/utils/request/reader.ts',
      'koodo-reader/src/constants/popupList.tsx',
      'koodo-reader/src/components/popups/popupBox',
    ],
    targetFiles: [
      'src/utils/bookAI.ts',
      'src/utils/bookLookup.ts',
      'src/layout/BookReaderModal.vue',
      'src/layout/book-reader/ReaderAIPanel.vue',
    ],
  },
  {
    id: 'reader-export',
    label: 'Annotation export',
    area: 'reader',
    status: 'partial',
    koodoSource: ['koodo-reader/src/utils/file/export.ts'],
    targetFiles: ['src/utils/bookAnnotationExport.ts', 'src/layout/BookReaderModal.vue'],
  },
  {
    id: 'reader-convert-ocr',
    label: 'Convert/OCR dialogs excluding account services',
    area: 'reader',
    status: 'missing',
    koodoSource: ['koodo-reader/src/components/dialogs/convertDialog'],
    targetFiles: ['src/layout/BookReaderModal.vue', 'src/utils/bookReader.ts'],
  },
  {
    id: 'shared-i18n-labels',
    label: 'Koodo English/Chinese labels',
    area: 'shared',
    status: 'partial',
    koodoSource: ['koodo-reader/src/i18n.tsx'],
    targetFiles: ['src/layout/PageBookLibrary.vue', 'src/layout/BookReaderModal.vue'],
  },
]

export function getIncompleteKoodoFeatures(): KoodoParityFeature[] {
  return KOODO_PARITY_FEATURES.filter((item) => item.status === 'missing' || item.status === 'partial')
}
