[package]
name = "mihomo_api"
edition = "2024"

[features]
debug = []

[dependencies]
reqwest = { version = "0.12.12", features = ["json"] }
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.140"

[dev-dependencies]
tokio = { version = "1.43.0", features = ["rt", "macros"] }