name: release Linux

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: ubuntu-latest 

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      run: |
        cd v2rayN 
        chmod 755 build-linux.sh
        ./build-linux.sh

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: v2rayN-linux
        path: |
          ./v2rayN/v2rayN-linux.zip

     